// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event_api.proto
// Protobuf Java Version: 4.33.5

package ru.event.listener.extension.keycloak.event.v1;

/**
 * <pre>
 * CreateAdminResponse represents the response for creating an admin event.
 * Currently empty as the operation is fire-and-forget.
 * </pre>
 *
 * Protobuf type {@code keycloak.event.v1.CreateAdminResponse}
 */
@com.google.protobuf.Generated
public final class CreateAdminResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:keycloak.event.v1.CreateAdminResponse)
    CreateAdminResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "CreateAdminResponse");
  }
  // Use CreateAdminResponse.newBuilder() to construct.
  private CreateAdminResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateAdminResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.event.listener.extension.keycloak.event.v1.EventApiProto.internal_static_keycloak_event_v1_CreateAdminResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.event.listener.extension.keycloak.event.v1.EventApiProto.internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.class, ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse)) {
      return super.equals(obj);
    }
    ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse other = (ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CreateAdminResponse represents the response for creating an admin event.
   * Currently empty as the operation is fire-and-forget.
   * </pre>
   *
   * Protobuf type {@code keycloak.event.v1.CreateAdminResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:keycloak.event.v1.CreateAdminResponse)
      ru.event.listener.extension.keycloak.event.v1.CreateAdminResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.event.listener.extension.keycloak.event.v1.EventApiProto.internal_static_keycloak_event_v1_CreateAdminResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.event.listener.extension.keycloak.event.v1.EventApiProto.internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.class, ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.Builder.class);
    }

    // Construct using ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.event.listener.extension.keycloak.event.v1.EventApiProto.internal_static_keycloak_event_v1_CreateAdminResponse_descriptor;
    }

    @java.lang.Override
    public ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse getDefaultInstanceForType() {
      return ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse build() {
      ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse buildPartial() {
      ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse result = new ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse) {
        return mergeFrom((ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse other) {
      if (other == ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:keycloak.event.v1.CreateAdminResponse)
  }

  // @@protoc_insertion_point(class_scope:keycloak.event.v1.CreateAdminResponse)
  private static final ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse();
  }

  public static ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAdminResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateAdminResponse>() {
    @java.lang.Override
    public CreateAdminResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateAdminResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAdminResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.event.listener.extension.keycloak.event.v1.CreateAdminResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

