// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event_api.proto
// Protobuf Java Version: 4.33.5

package ru.event.listener.extension.keycloak.event.v1;

@com.google.protobuf.Generated
public final class EventApiProto extends com.google.protobuf.GeneratedFile {
  private EventApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "EventApiProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!keycloak/event/v1/event_api.proto\022\021key" +
      "cloak.event.v1\032\035keycloak/event/v1/event." +
      "proto\032\037google/protobuf/timestamp.proto\032\027" +
      "validate/validate.proto\"\267\006\n\022CreateAdminR" +
      "equest\022\030\n\002id\030\001 \001(\tB\010\372B\005r\003\260\001\001R\002id\0228\n\004time" +
      "\030\002 \001(\0132\032.google.protobuf.TimestampB\010\372B\005\262" +
      "\001\002\010\001R\004time\022#\n\010realm_id\030\003 \001(\tB\010\372B\005r\003\260\001\001R\007" +
      "realmId\022\035\n\nrealm_name\030\004 \001(\tR\trealmName\022T" +
      "\n\014auth_details\030\005 \001(\01321.keycloak.event.v1" +
      ".CreateAdminRequest.AuthDetailsR\013authDet" +
      "ails\022#\n\rresource_type\030\006 \001(\tR\014resourceTyp" +
      "e\022Q\n\016operation_type\030\007 \001(\0162 .keycloak.eve" +
      "nt.v1.OperationTypeB\010\372B\005\202\001\002\020\001R\roperation" +
      "Type\022#\n\rresource_path\030\010 \001(\tR\014resourcePat" +
      "h\022&\n\016representation\030\t \001(\tR\016representatio" +
      "n\022\024\n\005error\030\n \001(\tR\005error\022V\n\007details\030\013 \003(\013" +
      "22.keycloak.event.v1.CreateAdminRequest." +
      "DetailsEntryB\010\372B\005\232\001\0020\001R\007details\032:\n\014Detai" +
      "lsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\t" +
      "R\005value:\0028\001\032\303\001\n\013AuthDetails\022#\n\010realm_id\030" +
      "\001 \001(\tB\010\372B\005r\003\260\001\001R\007realmId\022\035\n\nrealm_name\030\002" +
      " \001(\tR\trealmName\022%\n\tclient_id\030\003 \001(\tB\010\372B\005r" +
      "\003\260\001\001R\010clientId\022!\n\007user_id\030\004 \001(\tB\010\372B\005r\003\260\001" +
      "\001R\006userId\022&\n\nip_address\030\005 \001(\tB\007\372B\004r\002p\001R\t" +
      "ipAddress\"\025\n\023CreateAdminResponse\"\243\004\n\rCre" +
      "ateRequest\022\030\n\002id\030\001 \001(\tB\010\372B\005r\003\260\001\001R\002id\0228\n\004" +
      "time\030\002 \001(\0132\032.google.protobuf.TimestampB\010" +
      "\372B\005\262\001\002\010\001R\004time\022:\n\004type\030\003 \001(\0162\034.keycloak." +
      "event.v1.EventTypeB\010\372B\005\202\001\002\020\001R\004type\022#\n\010re" +
      "alm_id\030\004 \001(\tB\010\372B\005r\003\260\001\001R\007realmId\022\035\n\nrealm" +
      "_name\030\005 \001(\tR\trealmName\022%\n\tclient_id\030\006 \001(" +
      "\tB\010\372B\005r\003\260\001\001R\010clientId\022!\n\007user_id\030\007 \001(\tB\010" +
      "\372B\005r\003\260\001\001R\006userId\022\'\n\nsession_id\030\010 \001(\tB\010\372B" +
      "\005r\003\260\001\001R\tsessionId\022&\n\nip_address\030\t \001(\tB\007\372" +
      "B\004r\002p\001R\tipAddress\022\024\n\005error\030\n \001(\tR\005error\022" +
      "Q\n\007details\030\013 \003(\0132-.keycloak.event.v1.Cre" +
      "ateRequest.DetailsEntryB\010\372B\005\232\001\0020\001R\007detai" +
      "ls\032:\n\014DetailsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005" +
      "value\030\002 \001(\tR\005value:\0028\001\"\020\n\016CreateResponse" +
      "2\273\001\n\010EventAPI\022^\n\013CreateAdmin\022%.keycloak." +
      "event.v1.CreateAdminRequest\032&.keycloak.e" +
      "vent.v1.CreateAdminResponse\"\000\022O\n\006Create\022" +
      " .keycloak.event.v1.CreateRequest\032!.keyc" +
      "loak.event.v1.CreateResponse\"\000B\277\001\n-ru.ev" +
      "ent.listener.extension.keycloak.event.v1" +
      "B\rEventApiProtoP\001Z\031keycloak/event/v1;eve" +
      "ntv1\242\002\003KEX\252\002\021Keycloak.Event.V1\312\002\021Keycloa" +
      "k\\Event\\V1\342\002\035Keycloak\\Event\\V1\\GPBMetada" +
      "ta\352\002\023Keycloak::Event::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ru.event.listener.extension.keycloak.event.v1.EventProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          ru.event.listener.extension.validate.ValidateProto.getDescriptor(),
        });
    internal_static_keycloak_event_v1_CreateAdminRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_keycloak_event_v1_CreateAdminRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_descriptor,
        new java.lang.String[] { "Id", "Time", "RealmId", "RealmName", "AuthDetails", "ResourceType", "OperationType", "ResourcePath", "Representation", "Error", "Details", });
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_CreateAdminRequest_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor =
      internal_static_keycloak_event_v1_CreateAdminRequest_descriptor.getNestedType(1);
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor,
        new java.lang.String[] { "RealmId", "RealmName", "ClientId", "UserId", "IpAddress", });
    internal_static_keycloak_event_v1_CreateAdminResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminResponse_descriptor,
        new java.lang.String[] { });
    internal_static_keycloak_event_v1_CreateRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_keycloak_event_v1_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateRequest_descriptor,
        new java.lang.String[] { "Id", "Time", "Type", "RealmId", "RealmName", "ClientId", "UserId", "SessionId", "IpAddress", "Error", "Details", });
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_CreateRequest_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keycloak_event_v1_CreateResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_keycloak_event_v1_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateResponse_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    ru.event.listener.extension.keycloak.event.v1.EventProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    ru.event.listener.extension.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(ru.event.listener.extension.validate.ValidateProto.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
