// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package ru.event.listener.extension.keycloak.event.v1;

/**
 * <pre>
 * Operation types for admin events
 * </pre>
 *
 * Protobuf enum {@code keycloak.event.v1.OperationType}
 */
@com.google.protobuf.Generated
public enum OperationType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Invalid operation type
   * </pre>
   *
   * <code>OPERATION_TYPE_INVALID = 0;</code>
   */
  OPERATION_TYPE_INVALID(0),
  /**
   * <pre>
   * Resource creation operation
   * </pre>
   *
   * <code>OPERATION_TYPE_CREATE = 1;</code>
   */
  OPERATION_TYPE_CREATE(1),
  /**
   * <pre>
   * Resource update operation
   * </pre>
   *
   * <code>OPERATION_TYPE_UPDATE = 2;</code>
   */
  OPERATION_TYPE_UPDATE(2),
  /**
   * <pre>
   * Resource deletion operation
   * </pre>
   *
   * <code>OPERATION_TYPE_DELETE = 3;</code>
   */
  OPERATION_TYPE_DELETE(3),
  /**
   * <pre>
   * Custom action operation
   * </pre>
   *
   * <code>OPERATION_TYPE_ACTION = 4;</code>
   */
  OPERATION_TYPE_ACTION(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "OperationType");
  }
  /**
   * <pre>
   * Invalid operation type
   * </pre>
   *
   * <code>OPERATION_TYPE_INVALID = 0;</code>
   */
  public static final int OPERATION_TYPE_INVALID_VALUE = 0;
  /**
   * <pre>
   * Resource creation operation
   * </pre>
   *
   * <code>OPERATION_TYPE_CREATE = 1;</code>
   */
  public static final int OPERATION_TYPE_CREATE_VALUE = 1;
  /**
   * <pre>
   * Resource update operation
   * </pre>
   *
   * <code>OPERATION_TYPE_UPDATE = 2;</code>
   */
  public static final int OPERATION_TYPE_UPDATE_VALUE = 2;
  /**
   * <pre>
   * Resource deletion operation
   * </pre>
   *
   * <code>OPERATION_TYPE_DELETE = 3;</code>
   */
  public static final int OPERATION_TYPE_DELETE_VALUE = 3;
  /**
   * <pre>
   * Custom action operation
   * </pre>
   *
   * <code>OPERATION_TYPE_ACTION = 4;</code>
   */
  public static final int OPERATION_TYPE_ACTION_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperationType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OperationType forNumber(int value) {
    switch (value) {
      case 0: return OPERATION_TYPE_INVALID;
      case 1: return OPERATION_TYPE_CREATE;
      case 2: return OPERATION_TYPE_UPDATE;
      case 3: return OPERATION_TYPE_DELETE;
      case 4: return OPERATION_TYPE_ACTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperationType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
          public OperationType findValueByNumber(int number) {
            return OperationType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ru.event.listener.extension.keycloak.event.v1.EventProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final OperationType[] VALUES = values();

  public static OperationType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperationType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:keycloak.event.v1.OperationType)
}

