// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

/**
 * <pre>
 * Admin event message for Keycloak administration operations
 * </pre>
 *
 * Protobuf type {@code keycloak.event.v1.AdminEvent}
 */
@com.google.protobuf.Generated
public final class AdminEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:keycloak.event.v1.AdminEvent)
    AdminEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "AdminEvent");
  }
  // Use AdminEvent.newBuilder() to construct.
  private AdminEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AdminEvent() {
    id_ = "";
    realmId_ = "";
    realmName_ = "";
    resourceType_ = "";
    operationType_ = 0;
    resourcePath_ = "";
    representation_ = "";
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 11:
        return internalGetDetails();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.keycloak.event.v1.AdminEvent.class, com.keycloak.event.v1.AdminEvent.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <pre>
   * Unique event identifier
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique event identifier
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp time_;
  /**
   * <pre>
   * Event timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return Whether the time field is set.
   */
  @java.lang.Override
  public boolean hasTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Event timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return The time.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <pre>
   * Event timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }

  public static final int REALM_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object realmId_ = "";
  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 3 [json_name = "realmId"];</code>
   * @return The realmId.
   */
  @java.lang.Override
  public java.lang.String getRealmId() {
    java.lang.Object ref = realmId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realmId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 3 [json_name = "realmId"];</code>
   * @return The bytes for realmId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRealmIdBytes() {
    java.lang.Object ref = realmId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realmId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REALM_NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object realmName_ = "";
  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 4 [json_name = "realmName"];</code>
   * @return The realmName.
   */
  @java.lang.Override
  public java.lang.String getRealmName() {
    java.lang.Object ref = realmName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realmName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 4 [json_name = "realmName"];</code>
   * @return The bytes for realmName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRealmNameBytes() {
    java.lang.Object ref = realmName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realmName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTH_DETAILS_FIELD_NUMBER = 5;
  private com.keycloak.event.v1.AuthDetails authDetails_;
  /**
   * <pre>
   * Authentication details
   * </pre>
   *
   * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   * @return Whether the authDetails field is set.
   */
  @java.lang.Override
  public boolean hasAuthDetails() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Authentication details
   * </pre>
   *
   * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   * @return The authDetails.
   */
  @java.lang.Override
  public com.keycloak.event.v1.AuthDetails getAuthDetails() {
    return authDetails_ == null ? com.keycloak.event.v1.AuthDetails.getDefaultInstance() : authDetails_;
  }
  /**
   * <pre>
   * Authentication details
   * </pre>
   *
   * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   */
  @java.lang.Override
  public com.keycloak.event.v1.AuthDetailsOrBuilder getAuthDetailsOrBuilder() {
    return authDetails_ == null ? com.keycloak.event.v1.AuthDetails.getDefaultInstance() : authDetails_;
  }

  public static final int RESOURCE_TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceType_ = "";
  /**
   * <pre>
   * Resource type
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Resource type
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_TYPE_FIELD_NUMBER = 7;
  private int operationType_ = 0;
  /**
   * <pre>
   * Operation type
   * </pre>
   *
   * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
   * @return The enum numeric value on the wire for operationType.
   */
  @java.lang.Override public int getOperationTypeValue() {
    return operationType_;
  }
  /**
   * <pre>
   * Operation type
   * </pre>
   *
   * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
   * @return The operationType.
   */
  @java.lang.Override public com.keycloak.event.v1.OperationType getOperationType() {
    com.keycloak.event.v1.OperationType result = com.keycloak.event.v1.OperationType.forNumber(operationType_);
    return result == null ? com.keycloak.event.v1.OperationType.UNRECOGNIZED : result;
  }

  public static final int RESOURCE_PATH_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourcePath_ = "";
  /**
   * <pre>
   * Resource path
   * </pre>
   *
   * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
   * @return The resourcePath.
   */
  @java.lang.Override
  public java.lang.String getResourcePath() {
    java.lang.Object ref = resourcePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourcePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Resource path
   * </pre>
   *
   * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
   * @return The bytes for resourcePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourcePathBytes() {
    java.lang.Object ref = resourcePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourcePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPRESENTATION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object representation_ = "";
  /**
   * <pre>
   * Resource representation
   * </pre>
   *
   * <code>string representation = 9 [json_name = "representation"];</code>
   * @return The representation.
   */
  @java.lang.Override
  public java.lang.String getRepresentation() {
    java.lang.Object ref = representation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      representation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Resource representation
   * </pre>
   *
   * <code>string representation = 9 [json_name = "representation"];</code>
   * @return The bytes for representation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRepresentationBytes() {
    java.lang.Object ref = representation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      representation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * Error message (if any)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Error message (if any)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAILS_FIELD_NUMBER = 11;
  private static final class DetailsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> details_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetDetails() {
    if (details_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DetailsDefaultEntryHolder.defaultEntry);
    }
    return details_;
  }
  public int getDetailsCount() {
    return internalGetDetails().getMap().size();
  }
  /**
   * <pre>
   * Additional event details
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  @java.lang.Override
  public boolean containsDetails(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetDetails().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getDetails() {
    return getDetailsMap();
  }
  /**
   * <pre>
   * Additional event details
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getDetailsMap() {
    return internalGetDetails().getMap();
  }
  /**
   * <pre>
   * Additional event details
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDetails().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Additional event details
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  @java.lang.Override
  public java.lang.String getDetailsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDetails().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTime());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, realmId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, realmName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getAuthDetails());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, resourceType_);
    }
    if (operationType_ != com.keycloak.event.v1.OperationType.OPERATION_TYPE_INVALID.getNumber()) {
      output.writeEnum(7, operationType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourcePath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, resourcePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(representation_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, representation_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, error_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetDetails(),
        DetailsDefaultEntryHolder.defaultEntry,
        11);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTime());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, realmId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, realmName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAuthDetails());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, resourceType_);
    }
    if (operationType_ != com.keycloak.event.v1.OperationType.OPERATION_TYPE_INVALID.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, operationType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourcePath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, resourcePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(representation_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, representation_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, error_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetDetails().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      details__ = DetailsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, details__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.keycloak.event.v1.AdminEvent)) {
      return super.equals(obj);
    }
    com.keycloak.event.v1.AdminEvent other = (com.keycloak.event.v1.AdminEvent) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasTime() != other.hasTime()) return false;
    if (hasTime()) {
      if (!getTime()
          .equals(other.getTime())) return false;
    }
    if (!getRealmId()
        .equals(other.getRealmId())) return false;
    if (!getRealmName()
        .equals(other.getRealmName())) return false;
    if (hasAuthDetails() != other.hasAuthDetails()) return false;
    if (hasAuthDetails()) {
      if (!getAuthDetails()
          .equals(other.getAuthDetails())) return false;
    }
    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (operationType_ != other.operationType_) return false;
    if (!getResourcePath()
        .equals(other.getResourcePath())) return false;
    if (!getRepresentation()
        .equals(other.getRepresentation())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!internalGetDetails().equals(
        other.internalGetDetails())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + REALM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRealmId().hashCode();
    hash = (37 * hash) + REALM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRealmName().hashCode();
    if (hasAuthDetails()) {
      hash = (37 * hash) + AUTH_DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthDetails().hashCode();
    }
    hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    hash = (37 * hash) + OPERATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + operationType_;
    hash = (37 * hash) + RESOURCE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getResourcePath().hashCode();
    hash = (37 * hash) + REPRESENTATION_FIELD_NUMBER;
    hash = (53 * hash) + getRepresentation().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (!internalGetDetails().getMap().isEmpty()) {
      hash = (37 * hash) + DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDetails().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.keycloak.event.v1.AdminEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.keycloak.event.v1.AdminEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.keycloak.event.v1.AdminEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.keycloak.event.v1.AdminEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.keycloak.event.v1.AdminEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Admin event message for Keycloak administration operations
   * </pre>
   *
   * Protobuf type {@code keycloak.event.v1.AdminEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:keycloak.event.v1.AdminEvent)
      com.keycloak.event.v1.AdminEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 11:
          return internalGetDetails();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 11:
          return internalGetMutableDetails();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keycloak.event.v1.AdminEvent.class, com.keycloak.event.v1.AdminEvent.Builder.class);
    }

    // Construct using com.keycloak.event.v1.AdminEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTimeFieldBuilder();
        internalGetAuthDetailsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      realmId_ = "";
      realmName_ = "";
      authDetails_ = null;
      if (authDetailsBuilder_ != null) {
        authDetailsBuilder_.dispose();
        authDetailsBuilder_ = null;
      }
      resourceType_ = "";
      operationType_ = 0;
      resourcePath_ = "";
      representation_ = "";
      error_ = "";
      internalGetMutableDetails().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AdminEvent_descriptor;
    }

    @java.lang.Override
    public com.keycloak.event.v1.AdminEvent getDefaultInstanceForType() {
      return com.keycloak.event.v1.AdminEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.keycloak.event.v1.AdminEvent build() {
      com.keycloak.event.v1.AdminEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.keycloak.event.v1.AdminEvent buildPartial() {
      com.keycloak.event.v1.AdminEvent result = new com.keycloak.event.v1.AdminEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.keycloak.event.v1.AdminEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.time_ = timeBuilder_ == null
            ? time_
            : timeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.realmId_ = realmId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.realmName_ = realmName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.authDetails_ = authDetailsBuilder_ == null
            ? authDetails_
            : authDetailsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.resourceType_ = resourceType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.operationType_ = operationType_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.resourcePath_ = resourcePath_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.representation_ = representation_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.error_ = error_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.details_ = internalGetDetails();
        result.details_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.keycloak.event.v1.AdminEvent) {
        return mergeFrom((com.keycloak.event.v1.AdminEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.keycloak.event.v1.AdminEvent other) {
      if (other == com.keycloak.event.v1.AdminEvent.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (!other.getRealmId().isEmpty()) {
        realmId_ = other.realmId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRealmName().isEmpty()) {
        realmName_ = other.realmName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasAuthDetails()) {
        mergeAuthDetails(other.getAuthDetails());
      }
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.operationType_ != 0) {
        setOperationTypeValue(other.getOperationTypeValue());
      }
      if (!other.getResourcePath().isEmpty()) {
        resourcePath_ = other.resourcePath_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getRepresentation().isEmpty()) {
        representation_ = other.representation_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      internalGetMutableDetails().mergeFrom(
          other.internalGetDetails());
      bitField0_ |= 0x00000400;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              realmId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              realmName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetAuthDetailsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              resourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              operationType_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              resourcePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              representation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              details__ = input.readMessage(
                  DetailsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableDetails().getMutableMap().put(
                  details__.getKey(), details__.getValue());
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Unique event identifier
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique event identifier
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique event identifier
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique event identifier
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique event identifier
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp time_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     * @return The time.
     */
    public com.google.protobuf.Timestamp getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
      } else {
        timeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      if (timeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          time_ != null &&
          time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimeBuilder().mergeFrom(value);
        } else {
          time_ = value;
        }
      } else {
        timeBuilder_.mergeFrom(value);
      }
      if (time_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      time_ = null;
      if (timeBuilder_ != null) {
        timeBuilder_.dispose();
        timeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : time_;
      }
    }
    /**
     * <pre>
     * Event timestamp
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private java.lang.Object realmId_ = "";
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 3 [json_name = "realmId"];</code>
     * @return The realmId.
     */
    public java.lang.String getRealmId() {
      java.lang.Object ref = realmId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realmId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 3 [json_name = "realmId"];</code>
     * @return The bytes for realmId.
     */
    public com.google.protobuf.ByteString
        getRealmIdBytes() {
      java.lang.Object ref = realmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 3 [json_name = "realmId"];</code>
     * @param value The realmId to set.
     * @return This builder for chaining.
     */
    public Builder setRealmId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      realmId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 3 [json_name = "realmId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRealmId() {
      realmId_ = getDefaultInstance().getRealmId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 3 [json_name = "realmId"];</code>
     * @param value The bytes for realmId to set.
     * @return This builder for chaining.
     */
    public Builder setRealmIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      realmId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object realmName_ = "";
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 4 [json_name = "realmName"];</code>
     * @return The realmName.
     */
    public java.lang.String getRealmName() {
      java.lang.Object ref = realmName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realmName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 4 [json_name = "realmName"];</code>
     * @return The bytes for realmName.
     */
    public com.google.protobuf.ByteString
        getRealmNameBytes() {
      java.lang.Object ref = realmName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 4 [json_name = "realmName"];</code>
     * @param value The realmName to set.
     * @return This builder for chaining.
     */
    public Builder setRealmName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      realmName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 4 [json_name = "realmName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRealmName() {
      realmName_ = getDefaultInstance().getRealmName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 4 [json_name = "realmName"];</code>
     * @param value The bytes for realmName to set.
     * @return This builder for chaining.
     */
    public Builder setRealmNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      realmName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.keycloak.event.v1.AuthDetails authDetails_;
    private com.google.protobuf.SingleFieldBuilder<
        com.keycloak.event.v1.AuthDetails, com.keycloak.event.v1.AuthDetails.Builder, com.keycloak.event.v1.AuthDetailsOrBuilder> authDetailsBuilder_;
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     * @return Whether the authDetails field is set.
     */
    public boolean hasAuthDetails() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     * @return The authDetails.
     */
    public com.keycloak.event.v1.AuthDetails getAuthDetails() {
      if (authDetailsBuilder_ == null) {
        return authDetails_ == null ? com.keycloak.event.v1.AuthDetails.getDefaultInstance() : authDetails_;
      } else {
        return authDetailsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public Builder setAuthDetails(com.keycloak.event.v1.AuthDetails value) {
      if (authDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authDetails_ = value;
      } else {
        authDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public Builder setAuthDetails(
        com.keycloak.event.v1.AuthDetails.Builder builderForValue) {
      if (authDetailsBuilder_ == null) {
        authDetails_ = builderForValue.build();
      } else {
        authDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public Builder mergeAuthDetails(com.keycloak.event.v1.AuthDetails value) {
      if (authDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          authDetails_ != null &&
          authDetails_ != com.keycloak.event.v1.AuthDetails.getDefaultInstance()) {
          getAuthDetailsBuilder().mergeFrom(value);
        } else {
          authDetails_ = value;
        }
      } else {
        authDetailsBuilder_.mergeFrom(value);
      }
      if (authDetails_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public Builder clearAuthDetails() {
      bitField0_ = (bitField0_ & ~0x00000010);
      authDetails_ = null;
      if (authDetailsBuilder_ != null) {
        authDetailsBuilder_.dispose();
        authDetailsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public com.keycloak.event.v1.AuthDetails.Builder getAuthDetailsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetAuthDetailsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    public com.keycloak.event.v1.AuthDetailsOrBuilder getAuthDetailsOrBuilder() {
      if (authDetailsBuilder_ != null) {
        return authDetailsBuilder_.getMessageOrBuilder();
      } else {
        return authDetails_ == null ?
            com.keycloak.event.v1.AuthDetails.getDefaultInstance() : authDetails_;
      }
    }
    /**
     * <pre>
     * Authentication details
     * </pre>
     *
     * <code>.keycloak.event.v1.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.keycloak.event.v1.AuthDetails, com.keycloak.event.v1.AuthDetails.Builder, com.keycloak.event.v1.AuthDetailsOrBuilder> 
        internalGetAuthDetailsFieldBuilder() {
      if (authDetailsBuilder_ == null) {
        authDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.keycloak.event.v1.AuthDetails, com.keycloak.event.v1.AuthDetails.Builder, com.keycloak.event.v1.AuthDetailsOrBuilder>(
                getAuthDetails(),
                getParentForChildren(),
                isClean());
        authDetails_ = null;
      }
      return authDetailsBuilder_;
    }

    private java.lang.Object resourceType_ = "";
    /**
     * <pre>
     * Resource type
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Resource type
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Resource type
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource type
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      resourceType_ = getDefaultInstance().getResourceType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource type
     * </pre>
     *
     * <code>string resource_type = 6 [json_name = "resourceType"];</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int operationType_ = 0;
    /**
     * <pre>
     * Operation type
     * </pre>
     *
     * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
     * @return The enum numeric value on the wire for operationType.
     */
    @java.lang.Override public int getOperationTypeValue() {
      return operationType_;
    }
    /**
     * <pre>
     * Operation type
     * </pre>
     *
     * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
     * @param value The enum numeric value on the wire for operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationTypeValue(int value) {
      operationType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operation type
     * </pre>
     *
     * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
     * @return The operationType.
     */
    @java.lang.Override
    public com.keycloak.event.v1.OperationType getOperationType() {
      com.keycloak.event.v1.OperationType result = com.keycloak.event.v1.OperationType.forNumber(operationType_);
      return result == null ? com.keycloak.event.v1.OperationType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Operation type
     * </pre>
     *
     * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
     * @param value The operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationType(com.keycloak.event.v1.OperationType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      operationType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operation type
     * </pre>
     *
     * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      operationType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resourcePath_ = "";
    /**
     * <pre>
     * Resource path
     * </pre>
     *
     * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
     * @return The resourcePath.
     */
    public java.lang.String getResourcePath() {
      java.lang.Object ref = resourcePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourcePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Resource path
     * </pre>
     *
     * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
     * @return The bytes for resourcePath.
     */
    public com.google.protobuf.ByteString
        getResourcePathBytes() {
      java.lang.Object ref = resourcePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourcePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Resource path
     * </pre>
     *
     * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
     * @param value The resourcePath to set.
     * @return This builder for chaining.
     */
    public Builder setResourcePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourcePath_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource path
     * </pre>
     *
     * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResourcePath() {
      resourcePath_ = getDefaultInstance().getResourcePath();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource path
     * </pre>
     *
     * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
     * @param value The bytes for resourcePath to set.
     * @return This builder for chaining.
     */
    public Builder setResourcePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourcePath_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object representation_ = "";
    /**
     * <pre>
     * Resource representation
     * </pre>
     *
     * <code>string representation = 9 [json_name = "representation"];</code>
     * @return The representation.
     */
    public java.lang.String getRepresentation() {
      java.lang.Object ref = representation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        representation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Resource representation
     * </pre>
     *
     * <code>string representation = 9 [json_name = "representation"];</code>
     * @return The bytes for representation.
     */
    public com.google.protobuf.ByteString
        getRepresentationBytes() {
      java.lang.Object ref = representation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        representation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Resource representation
     * </pre>
     *
     * <code>string representation = 9 [json_name = "representation"];</code>
     * @param value The representation to set.
     * @return This builder for chaining.
     */
    public Builder setRepresentation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      representation_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource representation
     * </pre>
     *
     * <code>string representation = 9 [json_name = "representation"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepresentation() {
      representation_ = getDefaultInstance().getRepresentation();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Resource representation
     * </pre>
     *
     * <code>string representation = 9 [json_name = "representation"];</code>
     * @param value The bytes for representation to set.
     * @return This builder for chaining.
     */
    public Builder setRepresentationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      representation_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * Error message (if any)
     * </pre>
     *
     * <code>string error = 10 [json_name = "error"];</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Error message (if any)
     * </pre>
     *
     * <code>string error = 10 [json_name = "error"];</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Error message (if any)
     * </pre>
     *
     * <code>string error = 10 [json_name = "error"];</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message (if any)
     * </pre>
     *
     * <code>string error = 10 [json_name = "error"];</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message (if any)
     * </pre>
     *
     * <code>string error = 10 [json_name = "error"];</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> details_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetDetails() {
      if (details_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DetailsDefaultEntryHolder.defaultEntry);
      }
      return details_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableDetails() {
      if (details_ == null) {
        details_ = com.google.protobuf.MapField.newMapField(
            DetailsDefaultEntryHolder.defaultEntry);
      }
      if (!details_.isMutable()) {
        details_ = details_.copy();
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return details_;
    }
    public int getDetailsCount() {
      return internalGetDetails().getMap().size();
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    @java.lang.Override
    public boolean containsDetails(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetDetails().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDetailsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDetails() {
      return getDetailsMap();
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getDetailsMap() {
      return internalGetDetails().getMap();
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getDetailsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDetails().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    @java.lang.Override
    public java.lang.String getDetailsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDetails().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearDetails() {
      bitField0_ = (bitField0_ & ~0x00000400);
      internalGetMutableDetails().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    public Builder removeDetails(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableDetails().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableDetails() {
      bitField0_ |= 0x00000400;
      return internalGetMutableDetails().getMutableMap();
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    public Builder putDetails(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableDetails().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <pre>
     * Additional event details
     * </pre>
     *
     * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
     */
    public Builder putAllDetails(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableDetails().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000400;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:keycloak.event.v1.AdminEvent)
  }

  // @@protoc_insertion_point(class_scope:keycloak.event.v1.AdminEvent)
  private static final com.keycloak.event.v1.AdminEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.keycloak.event.v1.AdminEvent();
  }

  public static com.keycloak.event.v1.AdminEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminEvent>
      PARSER = new com.google.protobuf.AbstractParser<AdminEvent>() {
    @java.lang.Override
    public AdminEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.keycloak.event.v1.AdminEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

