// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

/**
 * <pre>
 * Authentication details for admin events
 * </pre>
 *
 * Protobuf type {@code keycloak.event.v1.AuthDetails}
 */
@com.google.protobuf.Generated
public final class AuthDetails extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:keycloak.event.v1.AuthDetails)
    AuthDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "AuthDetails");
  }
  // Use AuthDetails.newBuilder() to construct.
  private AuthDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuthDetails() {
    realmId_ = "";
    realmName_ = "";
    clientId_ = "";
    userId_ = "";
    ipAddress_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AuthDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AuthDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.keycloak.event.v1.AuthDetails.class, com.keycloak.event.v1.AuthDetails.Builder.class);
  }

  public static final int REALM_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object realmId_ = "";
  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 1 [json_name = "realmId"];</code>
   * @return The realmId.
   */
  @java.lang.Override
  public java.lang.String getRealmId() {
    java.lang.Object ref = realmId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realmId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 1 [json_name = "realmId"];</code>
   * @return The bytes for realmId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRealmIdBytes() {
    java.lang.Object ref = realmId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realmId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REALM_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object realmName_ = "";
  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 2 [json_name = "realmName"];</code>
   * @return The realmName.
   */
  @java.lang.Override
  public java.lang.String getRealmName() {
    java.lang.Object ref = realmName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realmName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 2 [json_name = "realmName"];</code>
   * @return The bytes for realmName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRealmNameBytes() {
    java.lang.Object ref = realmName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realmName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientId_ = "";
  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 3 [json_name = "clientId"];</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 3 [json_name = "clientId"];</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * User identifier
   * </pre>
   *
   * <code>string user_id = 4 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * User identifier
   * </pre>
   *
   * <code>string user_id = 4 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_ADDRESS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipAddress_ = "";
  /**
   * <pre>
   * IP address of the client
   * </pre>
   *
   * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
   * @return The ipAddress.
   */
  @java.lang.Override
  public java.lang.String getIpAddress() {
    java.lang.Object ref = ipAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * IP address of the client
   * </pre>
   *
   * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
   * @return The bytes for ipAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpAddressBytes() {
    java.lang.Object ref = ipAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, realmId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, realmName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, clientId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, ipAddress_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, realmId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(realmName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, realmName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, clientId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, ipAddress_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.keycloak.event.v1.AuthDetails)) {
      return super.equals(obj);
    }
    com.keycloak.event.v1.AuthDetails other = (com.keycloak.event.v1.AuthDetails) obj;

    if (!getRealmId()
        .equals(other.getRealmId())) return false;
    if (!getRealmName()
        .equals(other.getRealmName())) return false;
    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getIpAddress()
        .equals(other.getIpAddress())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REALM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRealmId().hashCode();
    hash = (37 * hash) + REALM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRealmName().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + IP_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getIpAddress().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.keycloak.event.v1.AuthDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.keycloak.event.v1.AuthDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.keycloak.event.v1.AuthDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.keycloak.event.v1.AuthDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.keycloak.event.v1.AuthDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Authentication details for admin events
   * </pre>
   *
   * Protobuf type {@code keycloak.event.v1.AuthDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:keycloak.event.v1.AuthDetails)
      com.keycloak.event.v1.AuthDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AuthDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AuthDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keycloak.event.v1.AuthDetails.class, com.keycloak.event.v1.AuthDetails.Builder.class);
    }

    // Construct using com.keycloak.event.v1.AuthDetails.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      realmId_ = "";
      realmName_ = "";
      clientId_ = "";
      userId_ = "";
      ipAddress_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.keycloak.event.v1.EventProto.internal_static_keycloak_event_v1_AuthDetails_descriptor;
    }

    @java.lang.Override
    public com.keycloak.event.v1.AuthDetails getDefaultInstanceForType() {
      return com.keycloak.event.v1.AuthDetails.getDefaultInstance();
    }

    @java.lang.Override
    public com.keycloak.event.v1.AuthDetails build() {
      com.keycloak.event.v1.AuthDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.keycloak.event.v1.AuthDetails buildPartial() {
      com.keycloak.event.v1.AuthDetails result = new com.keycloak.event.v1.AuthDetails(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.keycloak.event.v1.AuthDetails result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.realmId_ = realmId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.realmName_ = realmName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.clientId_ = clientId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ipAddress_ = ipAddress_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.keycloak.event.v1.AuthDetails) {
        return mergeFrom((com.keycloak.event.v1.AuthDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.keycloak.event.v1.AuthDetails other) {
      if (other == com.keycloak.event.v1.AuthDetails.getDefaultInstance()) return this;
      if (!other.getRealmId().isEmpty()) {
        realmId_ = other.realmId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRealmName().isEmpty()) {
        realmName_ = other.realmName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getIpAddress().isEmpty()) {
        ipAddress_ = other.ipAddress_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              realmId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              realmName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              clientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              ipAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object realmId_ = "";
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 1 [json_name = "realmId"];</code>
     * @return The realmId.
     */
    public java.lang.String getRealmId() {
      java.lang.Object ref = realmId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realmId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 1 [json_name = "realmId"];</code>
     * @return The bytes for realmId.
     */
    public com.google.protobuf.ByteString
        getRealmIdBytes() {
      java.lang.Object ref = realmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 1 [json_name = "realmId"];</code>
     * @param value The realmId to set.
     * @return This builder for chaining.
     */
    public Builder setRealmId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      realmId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 1 [json_name = "realmId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRealmId() {
      realmId_ = getDefaultInstance().getRealmId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm identifier
     * </pre>
     *
     * <code>string realm_id = 1 [json_name = "realmId"];</code>
     * @param value The bytes for realmId to set.
     * @return This builder for chaining.
     */
    public Builder setRealmIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      realmId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object realmName_ = "";
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 2 [json_name = "realmName"];</code>
     * @return The realmName.
     */
    public java.lang.String getRealmName() {
      java.lang.Object ref = realmName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realmName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 2 [json_name = "realmName"];</code>
     * @return The bytes for realmName.
     */
    public com.google.protobuf.ByteString
        getRealmNameBytes() {
      java.lang.Object ref = realmName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 2 [json_name = "realmName"];</code>
     * @param value The realmName to set.
     * @return This builder for chaining.
     */
    public Builder setRealmName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      realmName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 2 [json_name = "realmName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRealmName() {
      realmName_ = getDefaultInstance().getRealmName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Realm name
     * </pre>
     *
     * <code>string realm_name = 2 [json_name = "realmName"];</code>
     * @param value The bytes for realmName to set.
     * @return This builder for chaining.
     */
    public Builder setRealmNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      realmName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     * Client identifier
     * </pre>
     *
     * <code>string client_id = 3 [json_name = "clientId"];</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Client identifier
     * </pre>
     *
     * <code>string client_id = 3 [json_name = "clientId"];</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Client identifier
     * </pre>
     *
     * <code>string client_id = 3 [json_name = "clientId"];</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client identifier
     * </pre>
     *
     * <code>string client_id = 3 [json_name = "clientId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      clientId_ = getDefaultInstance().getClientId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Client identifier
     * </pre>
     *
     * <code>string client_id = 3 [json_name = "clientId"];</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * User identifier
     * </pre>
     *
     * <code>string user_id = 4 [json_name = "userId"];</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * User identifier
     * </pre>
     *
     * <code>string user_id = 4 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * User identifier
     * </pre>
     *
     * <code>string user_id = 4 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User identifier
     * </pre>
     *
     * <code>string user_id = 4 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User identifier
     * </pre>
     *
     * <code>string user_id = 4 [json_name = "userId"];</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object ipAddress_ = "";
    /**
     * <pre>
     * IP address of the client
     * </pre>
     *
     * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
     * @return The ipAddress.
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * IP address of the client
     * </pre>
     *
     * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
     * @return The bytes for ipAddress.
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * IP address of the client
     * </pre>
     *
     * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
     * @param value The ipAddress to set.
     * @return This builder for chaining.
     */
    public Builder setIpAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IP address of the client
     * </pre>
     *
     * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIpAddress() {
      ipAddress_ = getDefaultInstance().getIpAddress();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IP address of the client
     * </pre>
     *
     * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
     * @param value The bytes for ipAddress to set.
     * @return This builder for chaining.
     */
    public Builder setIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:keycloak.event.v1.AuthDetails)
  }

  // @@protoc_insertion_point(class_scope:keycloak.event.v1.AuthDetails)
  private static final com.keycloak.event.v1.AuthDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.keycloak.event.v1.AuthDetails();
  }

  public static com.keycloak.event.v1.AuthDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthDetails>
      PARSER = new com.google.protobuf.AbstractParser<AuthDetails>() {
    @java.lang.Override
    public AuthDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.keycloak.event.v1.AuthDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

