// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

@com.google.protobuf.Generated
public interface AuthDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keycloak.event.v1.AuthDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 1 [json_name = "realmId"];</code>
   * @return The realmId.
   */
  java.lang.String getRealmId();
  /**
   * <pre>
   * Realm identifier
   * </pre>
   *
   * <code>string realm_id = 1 [json_name = "realmId"];</code>
   * @return The bytes for realmId.
   */
  com.google.protobuf.ByteString
      getRealmIdBytes();

  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 2 [json_name = "realmName"];</code>
   * @return The realmName.
   */
  java.lang.String getRealmName();
  /**
   * <pre>
   * Realm name
   * </pre>
   *
   * <code>string realm_name = 2 [json_name = "realmName"];</code>
   * @return The bytes for realmName.
   */
  com.google.protobuf.ByteString
      getRealmNameBytes();

  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 3 [json_name = "clientId"];</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Client identifier
   * </pre>
   *
   * <code>string client_id = 3 [json_name = "clientId"];</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * User identifier
   * </pre>
   *
   * <code>string user_id = 4 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * User identifier
   * </pre>
   *
   * <code>string user_id = 4 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * IP address of the client
   * </pre>
   *
   * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <pre>
   * IP address of the client
   * </pre>
   *
   * <code>string ip_address = 5 [json_name = "ipAddress"];</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();
}
