// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event_api.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

@com.google.protobuf.Generated
public interface CreateAdminRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keycloak.event.v1.CreateAdminRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the admin event
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier for the admin event
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Timestamp when the admin event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <pre>
   * Timestamp when the admin event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <pre>
   * Timestamp when the admin event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <pre>
   * Unique identifier of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_id = 3 [json_name = "realmId"];</code>
   * @return The realmId.
   */
  java.lang.String getRealmId();
  /**
   * <pre>
   * Unique identifier of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_id = 3 [json_name = "realmId"];</code>
   * @return The bytes for realmId.
   */
  com.google.protobuf.ByteString
      getRealmIdBytes();

  /**
   * <pre>
   * Name of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_name = 4 [json_name = "realmName"];</code>
   * @return The realmName.
   */
  java.lang.String getRealmName();
  /**
   * <pre>
   * Name of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_name = 4 [json_name = "realmName"];</code>
   * @return The bytes for realmName.
   */
  com.google.protobuf.ByteString
      getRealmNameBytes();

  /**
   * <pre>
   * Authentication details of the user or client who performed the operation
   * </pre>
   *
   * <code>.keycloak.event.v1.CreateAdminRequest.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   * @return Whether the authDetails field is set.
   */
  boolean hasAuthDetails();
  /**
   * <pre>
   * Authentication details of the user or client who performed the operation
   * </pre>
   *
   * <code>.keycloak.event.v1.CreateAdminRequest.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   * @return The authDetails.
   */
  com.keycloak.event.v1.CreateAdminRequest.AuthDetails getAuthDetails();
  /**
   * <pre>
   * Authentication details of the user or client who performed the operation
   * </pre>
   *
   * <code>.keycloak.event.v1.CreateAdminRequest.AuthDetails auth_details = 5 [json_name = "authDetails"];</code>
   */
  com.keycloak.event.v1.CreateAdminRequest.AuthDetailsOrBuilder getAuthDetailsOrBuilder();

  /**
   * <pre>
   * Type of resource that was affected by the operation (e.g., user, client, realm)
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The resourceType.
   */
  java.lang.String getResourceType();
  /**
   * <pre>
   * Type of resource that was affected by the operation (e.g., user, client, realm)
   * </pre>
   *
   * <code>string resource_type = 6 [json_name = "resourceType"];</code>
   * @return The bytes for resourceType.
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();

  /**
   * <pre>
   * Type of operation performed (create, update, delete, action)
   * </pre>
   *
   * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
   * @return The enum numeric value on the wire for operationType.
   */
  int getOperationTypeValue();
  /**
   * <pre>
   * Type of operation performed (create, update, delete, action)
   * </pre>
   *
   * <code>.keycloak.event.v1.OperationType operation_type = 7 [json_name = "operationType"];</code>
   * @return The operationType.
   */
  com.keycloak.event.v1.OperationType getOperationType();

  /**
   * <pre>
   * Path to the resource that was affected by the operation
   * </pre>
   *
   * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
   * @return The resourcePath.
   */
  java.lang.String getResourcePath();
  /**
   * <pre>
   * Path to the resource that was affected by the operation
   * </pre>
   *
   * <code>string resource_path = 8 [json_name = "resourcePath"];</code>
   * @return The bytes for resourcePath.
   */
  com.google.protobuf.ByteString
      getResourcePathBytes();

  /**
   * <pre>
   * Representation of the resource after the operation (optional)
   * </pre>
   *
   * <code>string representation = 9 [json_name = "representation"];</code>
   * @return The representation.
   */
  java.lang.String getRepresentation();
  /**
   * <pre>
   * Representation of the resource after the operation (optional)
   * </pre>
   *
   * <code>string representation = 9 [json_name = "representation"];</code>
   * @return The bytes for representation.
   */
  com.google.protobuf.ByteString
      getRepresentationBytes();

  /**
   * <pre>
   * Error message if the operation failed (optional)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   * Error message if the operation failed (optional)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  int getDetailsCount();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  boolean containsDetails(
      java.lang.String key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDetails();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDetailsMap();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  /* nullable */
java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  java.lang.String getDetailsOrThrow(
      java.lang.String key);
}
