// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event_api.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

@com.google.protobuf.Generated
public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:keycloak.event.v1.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the event
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier for the event
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Timestamp when the event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <pre>
   * Timestamp when the event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <pre>
   * Timestamp when the event occurred
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 2 [json_name = "time"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <pre>
   * Type of event that occurred (login, logout, token exchange, etc.)
   * </pre>
   *
   * <code>.keycloak.event.v1.EventType type = 3 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Type of event that occurred (login, logout, token exchange, etc.)
   * </pre>
   *
   * <code>.keycloak.event.v1.EventType type = 3 [json_name = "type"];</code>
   * @return The type.
   */
  com.keycloak.event.v1.EventType getType();

  /**
   * <pre>
   * Unique identifier of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_id = 4 [json_name = "realmId"];</code>
   * @return The realmId.
   */
  java.lang.String getRealmId();
  /**
   * <pre>
   * Unique identifier of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_id = 4 [json_name = "realmId"];</code>
   * @return The bytes for realmId.
   */
  com.google.protobuf.ByteString
      getRealmIdBytes();

  /**
   * <pre>
   * Name of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_name = 5 [json_name = "realmName"];</code>
   * @return The realmName.
   */
  java.lang.String getRealmName();
  /**
   * <pre>
   * Name of the realm where the event occurred
   * </pre>
   *
   * <code>string realm_name = 5 [json_name = "realmName"];</code>
   * @return The bytes for realmName.
   */
  com.google.protobuf.ByteString
      getRealmNameBytes();

  /**
   * <pre>
   * Unique identifier of the client involved in the event
   * </pre>
   *
   * <code>string client_id = 6 [json_name = "clientId"];</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Unique identifier of the client involved in the event
   * </pre>
   *
   * <code>string client_id = 6 [json_name = "clientId"];</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * Unique identifier of the user involved in the event
   * </pre>
   *
   * <code>string user_id = 7 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * Unique identifier of the user involved in the event
   * </pre>
   *
   * <code>string user_id = 7 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * Unique identifier of the user session
   * </pre>
   *
   * <code>string session_id = 8 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * Unique identifier of the user session
   * </pre>
   *
   * <code>string session_id = 8 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * IP address of the client that initiated the event
   * </pre>
   *
   * <code>string ip_address = 9 [json_name = "ipAddress"];</code>
   * @return The ipAddress.
   */
  java.lang.String getIpAddress();
  /**
   * <pre>
   * IP address of the client that initiated the event
   * </pre>
   *
   * <code>string ip_address = 9 [json_name = "ipAddress"];</code>
   * @return The bytes for ipAddress.
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <pre>
   * Error message if the event represents a failed operation (optional)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   * Error message if the event represents a failed operation (optional)
   * </pre>
   *
   * <code>string error = 10 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  int getDetailsCount();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  boolean containsDetails(
      java.lang.String key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDetails();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDetailsMap();
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  /* nullable */
java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Additional details about the event in key-value pairs
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 11 [json_name = "details"];</code>
   */
  java.lang.String getDetailsOrThrow(
      java.lang.String key);
}
