// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event_api.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

@com.google.protobuf.Generated
public final class EventApiProto extends com.google.protobuf.GeneratedFile {
  private EventApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "EventApiProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateAdminResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_CreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!keycloak/event/v1/event_api.proto\022\021key" +
      "cloak.event.v1\032\035keycloak/event/v1/event." +
      "proto\032\037google/protobuf/timestamp.proto\"\336" +
      "\005\n\022CreateAdminRequest\022\016\n\002id\030\001 \001(\tR\002id\022.\n" +
      "\004time\030\002 \001(\0132\032.google.protobuf.TimestampR" +
      "\004time\022\031\n\010realm_id\030\003 \001(\tR\007realmId\022\035\n\nreal" +
      "m_name\030\004 \001(\tR\trealmName\022T\n\014auth_details\030" +
      "\005 \001(\01321.keycloak.event.v1.CreateAdminReq" +
      "uest.AuthDetailsR\013authDetails\022#\n\rresourc" +
      "e_type\030\006 \001(\tR\014resourceType\022G\n\016operation_" +
      "type\030\007 \001(\0162 .keycloak.event.v1.Operation" +
      "TypeR\roperationType\022#\n\rresource_path\030\010 \001" +
      "(\tR\014resourcePath\022&\n\016representation\030\t \001(\t" +
      "R\016representation\022\024\n\005error\030\n \001(\tR\005error\022L" +
      "\n\007details\030\013 \003(\01322.keycloak.event.v1.Crea" +
      "teAdminRequest.DetailsEntryR\007details\032:\n\014" +
      "DetailsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030" +
      "\002 \001(\tR\005value:\0028\001\032\234\001\n\013AuthDetails\022\031\n\010real" +
      "m_id\030\001 \001(\tR\007realmId\022\035\n\nrealm_name\030\002 \001(\tR" +
      "\trealmName\022\033\n\tclient_id\030\003 \001(\tR\010clientId\022" +
      "\027\n\007user_id\030\004 \001(\tR\006userId\022\035\n\nip_address\030\005" +
      " \001(\tR\tipAddress\"\025\n\023CreateAdminResponse\"\312" +
      "\003\n\rCreateRequest\022\016\n\002id\030\001 \001(\tR\002id\022.\n\004time" +
      "\030\002 \001(\0132\032.google.protobuf.TimestampR\004time" +
      "\0220\n\004type\030\003 \001(\0162\034.keycloak.event.v1.Event" +
      "TypeR\004type\022\031\n\010realm_id\030\004 \001(\tR\007realmId\022\035\n" +
      "\nrealm_name\030\005 \001(\tR\trealmName\022\033\n\tclient_i" +
      "d\030\006 \001(\tR\010clientId\022\027\n\007user_id\030\007 \001(\tR\006user" +
      "Id\022\035\n\nsession_id\030\010 \001(\tR\tsessionId\022\035\n\nip_" +
      "address\030\t \001(\tR\tipAddress\022\024\n\005error\030\n \001(\tR" +
      "\005error\022G\n\007details\030\013 \003(\0132-.keycloak.event" +
      ".v1.CreateRequest.DetailsEntryR\007details\032" +
      ":\n\014DetailsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005val" +
      "ue\030\002 \001(\tR\005value:\0028\001\"\020\n\016CreateResponse2\273\001" +
      "\n\010EventAPI\022^\n\013CreateAdmin\022%.keycloak.eve" +
      "nt.v1.CreateAdminRequest\032&.keycloak.even" +
      "t.v1.CreateAdminResponse\"\000\022O\n\006Create\022 .k" +
      "eycloak.event.v1.CreateRequest\032!.keycloa" +
      "k.event.v1.CreateResponse\"\000Bq\n\025com.keycl" +
      "oak.event.v1B\rEventApiProtoP\001Z\031keycloak/" +
      "event/v1;eventv1\242\002\003CKE\252\002\021Keycloak.Event." +
      "V1\312\002\021Keycloak\\Event\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.keycloak.event.v1.EventProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_keycloak_event_v1_CreateAdminRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_keycloak_event_v1_CreateAdminRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_descriptor,
        new java.lang.String[] { "Id", "Time", "RealmId", "RealmName", "AuthDetails", "ResourceType", "OperationType", "ResourcePath", "Representation", "Error", "Details", });
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_CreateAdminRequest_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor =
      internal_static_keycloak_event_v1_CreateAdminRequest_descriptor.getNestedType(1);
    internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminRequest_AuthDetails_descriptor,
        new java.lang.String[] { "RealmId", "RealmName", "ClientId", "UserId", "IpAddress", });
    internal_static_keycloak_event_v1_CreateAdminResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_keycloak_event_v1_CreateAdminResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateAdminResponse_descriptor,
        new java.lang.String[] { });
    internal_static_keycloak_event_v1_CreateRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_keycloak_event_v1_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateRequest_descriptor,
        new java.lang.String[] { "Id", "Time", "Type", "RealmId", "RealmName", "ClientId", "UserId", "SessionId", "IpAddress", "Error", "Details", });
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_CreateRequest_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateRequest_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keycloak_event_v1_CreateResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_keycloak_event_v1_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_CreateResponse_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    com.keycloak.event.v1.EventProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
