// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

@com.google.protobuf.Generated
public final class EventProto extends com.google.protobuf.GeneratedFile {
  private EventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "EventProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_AuthDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_AuthDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_AdminEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_AdminEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_keycloak_event_v1_Event_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_keycloak_event_v1_Event_DetailsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035keycloak/event/v1/event.proto\022\021keycloa" +
      "k.event.v1\032\037google/protobuf/timestamp.pr" +
      "oto\"\234\001\n\013AuthDetails\022\031\n\010realm_id\030\001 \001(\tR\007r" +
      "ealmId\022\035\n\nrealm_name\030\002 \001(\tR\trealmName\022\033\n" +
      "\tclient_id\030\003 \001(\tR\010clientId\022\027\n\007user_id\030\004 " +
      "\001(\tR\006userId\022\035\n\nip_address\030\005 \001(\tR\tipAddre" +
      "ss\"\234\004\n\nAdminEvent\022\016\n\002id\030\001 \001(\tR\002id\022.\n\004tim" +
      "e\030\002 \001(\0132\032.google.protobuf.TimestampR\004tim" +
      "e\022\031\n\010realm_id\030\003 \001(\tR\007realmId\022\035\n\nrealm_na" +
      "me\030\004 \001(\tR\trealmName\022A\n\014auth_details\030\005 \001(" +
      "\0132\036.keycloak.event.v1.AuthDetailsR\013authD" +
      "etails\022#\n\rresource_type\030\006 \001(\tR\014resourceT" +
      "ype\022G\n\016operation_type\030\007 \001(\0162 .keycloak.e" +
      "vent.v1.OperationTypeR\roperationType\022#\n\r" +
      "resource_path\030\010 \001(\tR\014resourcePath\022&\n\016rep" +
      "resentation\030\t \001(\tR\016representation\022\024\n\005err" +
      "or\030\n \001(\tR\005error\022D\n\007details\030\013 \003(\0132*.keycl" +
      "oak.event.v1.AdminEvent.DetailsEntryR\007de" +
      "tails\032:\n\014DetailsEntry\022\020\n\003key\030\001 \001(\tR\003key\022" +
      "\024\n\005value\030\002 \001(\tR\005value:\0028\001\"\272\003\n\005Event\022\016\n\002i" +
      "d\030\001 \001(\tR\002id\022.\n\004time\030\002 \001(\0132\032.google.proto" +
      "buf.TimestampR\004time\0220\n\004type\030\003 \001(\0162\034.keyc" +
      "loak.event.v1.EventTypeR\004type\022\031\n\010realm_i" +
      "d\030\004 \001(\tR\007realmId\022\035\n\nrealm_name\030\005 \001(\tR\tre" +
      "almName\022\033\n\tclient_id\030\006 \001(\tR\010clientId\022\027\n\007" +
      "user_id\030\007 \001(\tR\006userId\022\035\n\nsession_id\030\010 \001(" +
      "\tR\tsessionId\022\035\n\nip_address\030\t \001(\tR\tipAddr" +
      "ess\022\024\n\005error\030\n \001(\tR\005error\022?\n\007details\030\013 \003" +
      "(\0132%.keycloak.event.v1.Event.DetailsEntr" +
      "yR\007details\032:\n\014DetailsEntry\022\020\n\003key\030\001 \001(\tR" +
      "\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001*\227\001\n\rOpera" +
      "tionType\022\032\n\026OPERATION_TYPE_INVALID\020\000\022\031\n\025" +
      "OPERATION_TYPE_CREATE\020\001\022\031\n\025OPERATION_TYP" +
      "E_UPDATE\020\002\022\031\n\025OPERATION_TYPE_DELETE\020\003\022\031\n" +
      "\025OPERATION_TYPE_ACTION\020\004*\277$\n\tEventType\022\026" +
      "\n\022EVENT_TYPE_INVALID\020\000\022\024\n\020EVENT_TYPE_LOG" +
      "IN\020\001\022\032\n\026EVENT_TYPE_LOGIN_ERROR\020\002\022\027\n\023EVEN" +
      "T_TYPE_REGISTER\020\003\022\035\n\031EVENT_TYPE_REGISTER" +
      "_ERROR\020\004\022\025\n\021EVENT_TYPE_LOGOUT\020\005\022\033\n\027EVENT" +
      "_TYPE_LOGOUT_ERROR\020\006\022\034\n\030EVENT_TYPE_CODE_" +
      "TO_TOKEN\020\007\022\"\n\036EVENT_TYPE_CODE_TO_TOKEN_E" +
      "RROR\020\010\022\033\n\027EVENT_TYPE_CLIENT_LOGIN\020\t\022!\n\035E" +
      "VENT_TYPE_CLIENT_LOGIN_ERROR\020\n\022\034\n\030EVENT_" +
      "TYPE_REFRESH_TOKEN\020\013\022\"\n\036EVENT_TYPE_REFRE" +
      "SH_TOKEN_ERROR\020\014\022(\n EVENT_TYPE_VALIDATE_" +
      "ACCESS_TOKEN\020\r\032\002\010\001\022.\n&EVENT_TYPE_VALIDAT" +
      "E_ACCESS_TOKEN_ERROR\020\016\032\002\010\001\022\037\n\033EVENT_TYPE" +
      "_INTROSPECT_TOKEN\020\017\022%\n!EVENT_TYPE_INTROS" +
      "PECT_TOKEN_ERROR\020\020\022&\n\"EVENT_TYPE_FEDERAT" +
      "ED_IDENTITY_LINK\020\021\022,\n(EVENT_TYPE_FEDERAT" +
      "ED_IDENTITY_LINK_ERROR\020\022\022(\n$EVENT_TYPE_R" +
      "EMOVE_FEDERATED_IDENTITY\020\023\022.\n*EVENT_TYPE" +
      "_REMOVE_FEDERATED_IDENTITY_ERROR\020\024\022\033\n\027EV" +
      "ENT_TYPE_UPDATE_EMAIL\020\025\022!\n\035EVENT_TYPE_UP" +
      "DATE_EMAIL_ERROR\020\026\022\035\n\031EVENT_TYPE_UPDATE_" +
      "PROFILE\020\027\022#\n\037EVENT_TYPE_UPDATE_PROFILE_E" +
      "RROR\020\030\022\"\n\032EVENT_TYPE_UPDATE_PASSWORD\020\031\032\002" +
      "\010\001\022(\n EVENT_TYPE_UPDATE_PASSWORD_ERROR\020\032" +
      "\032\002\010\001\022\036\n\026EVENT_TYPE_UPDATE_TOTP\020\033\032\002\010\001\022$\n\034" +
      "EVENT_TYPE_UPDATE_TOTP_ERROR\020\034\032\002\010\001\022\033\n\027EV" +
      "ENT_TYPE_VERIFY_EMAIL\020\035\022!\n\035EVENT_TYPE_VE" +
      "RIFY_EMAIL_ERROR\020\036\022\035\n\031EVENT_TYPE_VERIFY_" +
      "PROFILE\020\037\022#\n\037EVENT_TYPE_VERIFY_PROFILE_E" +
      "RROR\020 \022\036\n\026EVENT_TYPE_REMOVE_TOTP\020!\032\002\010\001\022$" +
      "\n\034EVENT_TYPE_REMOVE_TOTP_ERROR\020\"\032\002\010\001\022\034\n\030" +
      "EVENT_TYPE_GRANT_CONSENT\020#\022\"\n\036EVENT_TYPE" +
      "_GRANT_CONSENT_ERROR\020$\022\035\n\031EVENT_TYPE_UPD" +
      "ATE_CONSENT\020%\022#\n\037EVENT_TYPE_UPDATE_CONSE" +
      "NT_ERROR\020&\022\033\n\027EVENT_TYPE_REVOKE_GRANT\020\'\022" +
      "!\n\035EVENT_TYPE_REVOKE_GRANT_ERROR\020(\022 \n\034EV" +
      "ENT_TYPE_SEND_VERIFY_EMAIL\020)\022&\n\"EVENT_TY" +
      "PE_SEND_VERIFY_EMAIL_ERROR\020*\022\"\n\036EVENT_TY" +
      "PE_SEND_RESET_PASSWORD\020+\022(\n$EVENT_TYPE_S" +
      "END_RESET_PASSWORD_ERROR\020,\022*\n&EVENT_TYPE" +
      "_SEND_IDENTITY_PROVIDER_LINK\020-\0220\n,EVENT_" +
      "TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR\020." +
      "\022\035\n\031EVENT_TYPE_RESET_PASSWORD\020/\022#\n\037EVENT" +
      "_TYPE_RESET_PASSWORD_ERROR\0200\022%\n!EVENT_TY" +
      "PE_RESTART_AUTHENTICATION\0201\022+\n\'EVENT_TYP" +
      "E_RESTART_AUTHENTICATION_ERROR\0202\022 \n\034EVEN" +
      "T_TYPE_INVALID_SIGNATURE\0203\022&\n\"EVENT_TYPE" +
      "_INVALID_SIGNATURE_ERROR\0204\022\034\n\030EVENT_TYPE" +
      "_REGISTER_NODE\0205\022\"\n\036EVENT_TYPE_REGISTER_" +
      "NODE_ERROR\0206\022\036\n\032EVENT_TYPE_UNREGISTER_NO" +
      "DE\0207\022$\n EVENT_TYPE_UNREGISTER_NODE_ERROR" +
      "\0208\022 \n\034EVENT_TYPE_USER_INFO_REQUEST\0209\022&\n\"" +
      "EVENT_TYPE_USER_INFO_REQUEST_ERROR\020:\022-\n)" +
      "EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUN" +
      "T\020;\0223\n/EVENT_TYPE_IDENTITY_PROVIDER_LINK" +
      "_ACCOUNT_ERROR\020<\022&\n\"EVENT_TYPE_IDENTITY_" +
      "PROVIDER_LOGIN\020=\022,\n(EVENT_TYPE_IDENTITY_" +
      "PROVIDER_LOGIN_ERROR\020>\022,\n(EVENT_TYPE_IDE" +
      "NTITY_PROVIDER_FIRST_LOGIN\020?\0222\n.EVENT_TY" +
      "PE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR\020@" +
      "\022+\n\'EVENT_TYPE_IDENTITY_PROVIDER_POST_LO" +
      "GIN\020A\0221\n-EVENT_TYPE_IDENTITY_PROVIDER_PO" +
      "ST_LOGIN_ERROR\020B\022)\n%EVENT_TYPE_IDENTITY_" +
      "PROVIDER_RESPONSE\020C\022/\n+EVENT_TYPE_IDENTI" +
      "TY_PROVIDER_RESPONSE_ERROR\020D\022/\n+EVENT_TY" +
      "PE_IDENTITY_PROVIDER_RETRIEVE_TOKEN\020E\0225\n" +
      "1EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_T" +
      "OKEN_ERROR\020F\022\032\n\026EVENT_TYPE_IMPERSONATE\020G" +
      "\022 \n\034EVENT_TYPE_IMPERSONATE_ERROR\020H\022%\n!EV" +
      "ENT_TYPE_CUSTOM_REQUIRED_ACTION\020I\022+\n\'EVE" +
      "NT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR\020J\022\036" +
      "\n\032EVENT_TYPE_EXECUTE_ACTIONS\020K\022$\n EVENT_" +
      "TYPE_EXECUTE_ACTIONS_ERROR\020L\022#\n\037EVENT_TY" +
      "PE_EXECUTE_ACTION_TOKEN\020M\022)\n%EVENT_TYPE_" +
      "EXECUTE_ACTION_TOKEN_ERROR\020N\022\032\n\026EVENT_TY" +
      "PE_CLIENT_INFO\020O\022 \n\034EVENT_TYPE_CLIENT_IN" +
      "FO_ERROR\020P\022\036\n\032EVENT_TYPE_CLIENT_REGISTER" +
      "\020Q\022$\n EVENT_TYPE_CLIENT_REGISTER_ERROR\020R" +
      "\022\034\n\030EVENT_TYPE_CLIENT_UPDATE\020S\022\"\n\036EVENT_" +
      "TYPE_CLIENT_UPDATE_ERROR\020T\022\034\n\030EVENT_TYPE" +
      "_CLIENT_DELETE\020U\022\"\n\036EVENT_TYPE_CLIENT_DE" +
      "LETE_ERROR\020V\022/\n+EVENT_TYPE_CLIENT_INITIA" +
      "TED_ACCOUNT_LINKING\020W\0225\n1EVENT_TYPE_CLIE" +
      "NT_INITIATED_ACCOUNT_LINKING_ERROR\020X\022\035\n\031" +
      "EVENT_TYPE_TOKEN_EXCHANGE\020Y\022#\n\037EVENT_TYP" +
      "E_TOKEN_EXCHANGE_ERROR\020Z\022!\n\035EVENT_TYPE_O" +
      "AUTH2_DEVICE_AUTH\020[\022\'\n#EVENT_TYPE_OAUTH2" +
      "_DEVICE_AUTH_ERROR\020\\\022-\n)EVENT_TYPE_OAUTH" +
      "2_DEVICE_VERIFY_USER_CODE\020]\0223\n/EVENT_TYP" +
      "E_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR\020^" +
      "\022*\n&EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOK" +
      "EN\020_\0220\n,EVENT_TYPE_OAUTH2_DEVICE_CODE_TO" +
      "_TOKEN_ERROR\020`\022!\n\035EVENT_TYPE_AUTHREQID_T" +
      "O_TOKEN\020a\022\'\n#EVENT_TYPE_AUTHREQID_TO_TOK" +
      "EN_ERROR\020b\022\037\n\033EVENT_TYPE_PERMISSION_TOKE" +
      "N\020c\022%\n!EVENT_TYPE_PERMISSION_TOKEN_ERROR" +
      "\020d\022\035\n\031EVENT_TYPE_DELETE_ACCOUNT\020e\022#\n\037EVE" +
      "NT_TYPE_DELETE_ACCOUNT_ERROR\020f\022+\n\'EVENT_" +
      "TYPE_PUSHED_AUTHORIZATION_REQUEST\020g\0221\n-E" +
      "VENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_E" +
      "RROR\020h\0221\n-EVENT_TYPE_USER_DISABLED_BY_PE" +
      "RMANENT_LOCKOUT\020i\0227\n3EVENT_TYPE_USER_DIS" +
      "ABLED_BY_PERMANENT_LOCKOUT_ERROR\020j\0221\n-EV" +
      "ENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCK" +
      "OUT\020k\0227\n3EVENT_TYPE_USER_DISABLED_BY_TEM" +
      "PORARY_LOCKOUT_ERROR\020l\022%\n!EVENT_TYPE_OAU" +
      "TH2_EXTENSION_GRANT\020m\022+\n\'EVENT_TYPE_OAUT" +
      "H2_EXTENSION_GRANT_ERROR\020n\022/\n+EVENT_TYPE" +
      "_FEDERATED_IDENTITY_OVERRIDE_LINK\020o\0225\n1E" +
      "VENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LI" +
      "NK_ERROR\020p\022 \n\034EVENT_TYPE_UPDATE_CREDENTI" +
      "AL\020q\022&\n\"EVENT_TYPE_UPDATE_CREDENTIAL_ERR" +
      "OR\020r\022 \n\034EVENT_TYPE_REMOVE_CREDENTIAL\020s\022&" +
      "\n\"EVENT_TYPE_REMOVE_CREDENTIAL_ERROR\020t\022\031" +
      "\n\025EVENT_TYPE_INVITE_ORG\020u\022\037\n\033EVENT_TYPE_" +
      "INVITE_ORG_ERROR\020v\022#\n\037EVENT_TYPE_USER_SE" +
      "SSION_DELETED\020w\022)\n%EVENT_TYPE_USER_SESSI" +
      "ON_DELETED_ERROR\020xBn\n\025com.keycloak.event" +
      ".v1B\nEventProtoP\001Z\031keycloak/event/v1;eve" +
      "ntv1\242\002\003CKE\252\002\021Keycloak.Event.V1\312\002\021Keycloa" +
      "k\\Event\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_keycloak_event_v1_AuthDetails_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_keycloak_event_v1_AuthDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_AuthDetails_descriptor,
        new java.lang.String[] { "RealmId", "RealmName", "ClientId", "UserId", "IpAddress", });
    internal_static_keycloak_event_v1_AdminEvent_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_keycloak_event_v1_AdminEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_AdminEvent_descriptor,
        new java.lang.String[] { "Id", "Time", "RealmId", "RealmName", "AuthDetails", "ResourceType", "OperationType", "ResourcePath", "Representation", "Error", "Details", });
    internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_AdminEvent_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_AdminEvent_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_keycloak_event_v1_Event_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_keycloak_event_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_Event_descriptor,
        new java.lang.String[] { "Id", "Time", "Type", "RealmId", "RealmName", "ClientId", "UserId", "SessionId", "IpAddress", "Error", "Details", });
    internal_static_keycloak_event_v1_Event_DetailsEntry_descriptor =
      internal_static_keycloak_event_v1_Event_descriptor.getNestedType(0);
    internal_static_keycloak_event_v1_Event_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_keycloak_event_v1_Event_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
