// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keycloak/event/v1/event.proto
// Protobuf Java Version: 4.33.5

package com.keycloak.event.v1;

/**
 * <pre>
 * Event types for authentication and authorization events
 * </pre>
 *
 * Protobuf enum {@code keycloak.event.v1.EventType}
 */
@com.google.protobuf.Generated
public enum EventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Invalid event type
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID = 0;</code>
   */
  EVENT_TYPE_INVALID(0),
  /**
   * <pre>
   * User login event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGIN = 1;</code>
   */
  EVENT_TYPE_LOGIN(1),
  /**
   * <pre>
   * User login error event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGIN_ERROR = 2;</code>
   */
  EVENT_TYPE_LOGIN_ERROR(2),
  /**
   * <pre>
   * User registration event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER = 3;</code>
   */
  EVENT_TYPE_REGISTER(3),
  /**
   * <pre>
   * User registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_ERROR = 4;</code>
   */
  EVENT_TYPE_REGISTER_ERROR(4),
  /**
   * <pre>
   * User logout event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGOUT = 5;</code>
   */
  EVENT_TYPE_LOGOUT(5),
  /**
   * <pre>
   * User logout error event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGOUT_ERROR = 6;</code>
   */
  EVENT_TYPE_LOGOUT_ERROR(6),
  /**
   * <pre>
   * Authorization code to token exchange event
   * </pre>
   *
   * <code>EVENT_TYPE_CODE_TO_TOKEN = 7;</code>
   */
  EVENT_TYPE_CODE_TO_TOKEN(7),
  /**
   * <pre>
   * Authorization code to token exchange error event
   * </pre>
   *
   * <code>EVENT_TYPE_CODE_TO_TOKEN_ERROR = 8;</code>
   */
  EVENT_TYPE_CODE_TO_TOKEN_ERROR(8),
  /**
   * <pre>
   * Client login event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_LOGIN = 9;</code>
   */
  EVENT_TYPE_CLIENT_LOGIN(9),
  /**
   * <pre>
   * Client login error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_LOGIN_ERROR = 10;</code>
   */
  EVENT_TYPE_CLIENT_LOGIN_ERROR(10),
  /**
   * <pre>
   * Refresh token event
   * </pre>
   *
   * <code>EVENT_TYPE_REFRESH_TOKEN = 11;</code>
   */
  EVENT_TYPE_REFRESH_TOKEN(11),
  /**
   * <pre>
   * Refresh token error event
   * </pre>
   *
   * <code>EVENT_TYPE_REFRESH_TOKEN_ERROR = 12;</code>
   */
  EVENT_TYPE_REFRESH_TOKEN_ERROR(12),
  /**
   * <pre>
   * Access token validation event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_VALIDATE_ACCESS_TOKEN = 13 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_VALIDATE_ACCESS_TOKEN(13),
  /**
   * <pre>
   * Access token validation error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_VALIDATE_ACCESS_TOKEN_ERROR = 14 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_VALIDATE_ACCESS_TOKEN_ERROR(14),
  /**
   * <pre>
   * Token introspection event
   * </pre>
   *
   * <code>EVENT_TYPE_INTROSPECT_TOKEN = 15;</code>
   */
  EVENT_TYPE_INTROSPECT_TOKEN(15),
  /**
   * <pre>
   * Token introspection error event
   * </pre>
   *
   * <code>EVENT_TYPE_INTROSPECT_TOKEN_ERROR = 16;</code>
   */
  EVENT_TYPE_INTROSPECT_TOKEN_ERROR(16),
  /**
   * <pre>
   * Federated identity link event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_LINK = 17;</code>
   */
  EVENT_TYPE_FEDERATED_IDENTITY_LINK(17),
  /**
   * <pre>
   * Federated identity link error event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_LINK_ERROR = 18;</code>
   */
  EVENT_TYPE_FEDERATED_IDENTITY_LINK_ERROR(18),
  /**
   * <pre>
   * Federated identity removal event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_FEDERATED_IDENTITY = 19;</code>
   */
  EVENT_TYPE_REMOVE_FEDERATED_IDENTITY(19),
  /**
   * <pre>
   * Federated identity removal error event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_ERROR = 20;</code>
   */
  EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_ERROR(20),
  /**
   * <pre>
   * Email update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_EMAIL = 21;</code>
   */
  EVENT_TYPE_UPDATE_EMAIL(21),
  /**
   * <pre>
   * Email update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_EMAIL_ERROR = 22;</code>
   */
  EVENT_TYPE_UPDATE_EMAIL_ERROR(22),
  /**
   * <pre>
   * Profile update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PROFILE = 23;</code>
   */
  EVENT_TYPE_UPDATE_PROFILE(23),
  /**
   * <pre>
   * Profile update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PROFILE_ERROR = 24;</code>
   */
  EVENT_TYPE_UPDATE_PROFILE_ERROR(24),
  /**
   * <pre>
   * Password update event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PASSWORD = 25 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_UPDATE_PASSWORD(25),
  /**
   * <pre>
   * Password update error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PASSWORD_ERROR = 26 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_UPDATE_PASSWORD_ERROR(26),
  /**
   * <pre>
   * TOTP update event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_TOTP = 27 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_UPDATE_TOTP(27),
  /**
   * <pre>
   * TOTP update error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_TOTP_ERROR = 28 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_UPDATE_TOTP_ERROR(28),
  /**
   * <pre>
   * Email verification event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_EMAIL = 29;</code>
   */
  EVENT_TYPE_VERIFY_EMAIL(29),
  /**
   * <pre>
   * Email verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_EMAIL_ERROR = 30;</code>
   */
  EVENT_TYPE_VERIFY_EMAIL_ERROR(30),
  /**
   * <pre>
   * Profile verification event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_PROFILE = 31;</code>
   */
  EVENT_TYPE_VERIFY_PROFILE(31),
  /**
   * <pre>
   * Profile verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_PROFILE_ERROR = 32;</code>
   */
  EVENT_TYPE_VERIFY_PROFILE_ERROR(32),
  /**
   * <pre>
   * TOTP removal event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_TOTP = 33 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_REMOVE_TOTP(33),
  /**
   * <pre>
   * TOTP removal error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_TOTP_ERROR = 34 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  EVENT_TYPE_REMOVE_TOTP_ERROR(34),
  /**
   * <pre>
   * Consent grant event
   * </pre>
   *
   * <code>EVENT_TYPE_GRANT_CONSENT = 35;</code>
   */
  EVENT_TYPE_GRANT_CONSENT(35),
  /**
   * <pre>
   * Consent grant error event
   * </pre>
   *
   * <code>EVENT_TYPE_GRANT_CONSENT_ERROR = 36;</code>
   */
  EVENT_TYPE_GRANT_CONSENT_ERROR(36),
  /**
   * <pre>
   * Consent update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CONSENT = 37;</code>
   */
  EVENT_TYPE_UPDATE_CONSENT(37),
  /**
   * <pre>
   * Consent update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CONSENT_ERROR = 38;</code>
   */
  EVENT_TYPE_UPDATE_CONSENT_ERROR(38),
  /**
   * <pre>
   * Consent revocation event
   * </pre>
   *
   * <code>EVENT_TYPE_REVOKE_GRANT = 39;</code>
   */
  EVENT_TYPE_REVOKE_GRANT(39),
  /**
   * <pre>
   * Consent revocation error event
   * </pre>
   *
   * <code>EVENT_TYPE_REVOKE_GRANT_ERROR = 40;</code>
   */
  EVENT_TYPE_REVOKE_GRANT_ERROR(40),
  /**
   * <pre>
   * Email verification send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_VERIFY_EMAIL = 41;</code>
   */
  EVENT_TYPE_SEND_VERIFY_EMAIL(41),
  /**
   * <pre>
   * Email verification send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_VERIFY_EMAIL_ERROR = 42;</code>
   */
  EVENT_TYPE_SEND_VERIFY_EMAIL_ERROR(42),
  /**
   * <pre>
   * Password reset send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_RESET_PASSWORD = 43;</code>
   */
  EVENT_TYPE_SEND_RESET_PASSWORD(43),
  /**
   * <pre>
   * Password reset send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_RESET_PASSWORD_ERROR = 44;</code>
   */
  EVENT_TYPE_SEND_RESET_PASSWORD_ERROR(44),
  /**
   * <pre>
   * Identity provider link send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK = 45;</code>
   */
  EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK(45),
  /**
   * <pre>
   * Identity provider link send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR = 46;</code>
   */
  EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR(46),
  /**
   * <pre>
   * Password reset event
   * </pre>
   *
   * <code>EVENT_TYPE_RESET_PASSWORD = 47;</code>
   */
  EVENT_TYPE_RESET_PASSWORD(47),
  /**
   * <pre>
   * Password reset error event
   * </pre>
   *
   * <code>EVENT_TYPE_RESET_PASSWORD_ERROR = 48;</code>
   */
  EVENT_TYPE_RESET_PASSWORD_ERROR(48),
  /**
   * <pre>
   * Authentication restart event
   * </pre>
   *
   * <code>EVENT_TYPE_RESTART_AUTHENTICATION = 49;</code>
   */
  EVENT_TYPE_RESTART_AUTHENTICATION(49),
  /**
   * <pre>
   * Authentication restart error event
   * </pre>
   *
   * <code>EVENT_TYPE_RESTART_AUTHENTICATION_ERROR = 50;</code>
   */
  EVENT_TYPE_RESTART_AUTHENTICATION_ERROR(50),
  /**
   * <pre>
   * Invalid signature event
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID_SIGNATURE = 51;</code>
   */
  EVENT_TYPE_INVALID_SIGNATURE(51),
  /**
   * <pre>
   * Invalid signature error event
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID_SIGNATURE_ERROR = 52;</code>
   */
  EVENT_TYPE_INVALID_SIGNATURE_ERROR(52),
  /**
   * <pre>
   * Node registration event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_NODE = 53;</code>
   */
  EVENT_TYPE_REGISTER_NODE(53),
  /**
   * <pre>
   * Node registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_NODE_ERROR = 54;</code>
   */
  EVENT_TYPE_REGISTER_NODE_ERROR(54),
  /**
   * <pre>
   * Node unregistration event
   * </pre>
   *
   * <code>EVENT_TYPE_UNREGISTER_NODE = 55;</code>
   */
  EVENT_TYPE_UNREGISTER_NODE(55),
  /**
   * <pre>
   * Node unregistration error event
   * </pre>
   *
   * <code>EVENT_TYPE_UNREGISTER_NODE_ERROR = 56;</code>
   */
  EVENT_TYPE_UNREGISTER_NODE_ERROR(56),
  /**
   * <pre>
   * User info request event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_INFO_REQUEST = 57;</code>
   */
  EVENT_TYPE_USER_INFO_REQUEST(57),
  /**
   * <pre>
   * User info request error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_INFO_REQUEST_ERROR = 58;</code>
   */
  EVENT_TYPE_USER_INFO_REQUEST_ERROR(58),
  /**
   * <pre>
   * Identity provider account linking event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT = 59;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT(59),
  /**
   * <pre>
   * Identity provider account linking error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR = 60;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR(60),
  /**
   * <pre>
   * Identity provider login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LOGIN = 61;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_LOGIN(61),
  /**
   * <pre>
   * Identity provider login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_ERROR = 62;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_ERROR(62),
  /**
   * <pre>
   * Identity provider first login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN = 63;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN(63),
  /**
   * <pre>
   * Identity provider first login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR = 64;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR(64),
  /**
   * <pre>
   * Identity provider post-login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN = 65;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN(65),
  /**
   * <pre>
   * Identity provider post-login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_ERROR = 66;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_ERROR(66),
  /**
   * <pre>
   * Identity provider response event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE = 67;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE(67),
  /**
   * <pre>
   * Identity provider response error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_ERROR = 68;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_ERROR(68),
  /**
   * <pre>
   * Identity provider token retrieval event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN = 69;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN(69),
  /**
   * <pre>
   * Identity provider token retrieval error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR = 70;</code>
   */
  EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR(70),
  /**
   * <pre>
   * User impersonation event
   * </pre>
   *
   * <code>EVENT_TYPE_IMPERSONATE = 71;</code>
   */
  EVENT_TYPE_IMPERSONATE(71),
  /**
   * <pre>
   * User impersonation error event
   * </pre>
   *
   * <code>EVENT_TYPE_IMPERSONATE_ERROR = 72;</code>
   */
  EVENT_TYPE_IMPERSONATE_ERROR(72),
  /**
   * <pre>
   * Custom required action event
   * </pre>
   *
   * <code>EVENT_TYPE_CUSTOM_REQUIRED_ACTION = 73;</code>
   */
  EVENT_TYPE_CUSTOM_REQUIRED_ACTION(73),
  /**
   * <pre>
   * Custom required action error event
   * </pre>
   *
   * <code>EVENT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR = 74;</code>
   */
  EVENT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR(74),
  /**
   * <pre>
   * Execute actions event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTIONS = 75;</code>
   */
  EVENT_TYPE_EXECUTE_ACTIONS(75),
  /**
   * <pre>
   * Execute actions error event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTIONS_ERROR = 76;</code>
   */
  EVENT_TYPE_EXECUTE_ACTIONS_ERROR(76),
  /**
   * <pre>
   * Execute action token event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTION_TOKEN = 77;</code>
   */
  EVENT_TYPE_EXECUTE_ACTION_TOKEN(77),
  /**
   * <pre>
   * Execute action token error event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTION_TOKEN_ERROR = 78;</code>
   */
  EVENT_TYPE_EXECUTE_ACTION_TOKEN_ERROR(78),
  /**
   * <pre>
   * Client info event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INFO = 79;</code>
   */
  EVENT_TYPE_CLIENT_INFO(79),
  /**
   * <pre>
   * Client info error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INFO_ERROR = 80;</code>
   */
  EVENT_TYPE_CLIENT_INFO_ERROR(80),
  /**
   * <pre>
   * Client registration event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_REGISTER = 81;</code>
   */
  EVENT_TYPE_CLIENT_REGISTER(81),
  /**
   * <pre>
   * Client registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_REGISTER_ERROR = 82;</code>
   */
  EVENT_TYPE_CLIENT_REGISTER_ERROR(82),
  /**
   * <pre>
   * Client update event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_UPDATE = 83;</code>
   */
  EVENT_TYPE_CLIENT_UPDATE(83),
  /**
   * <pre>
   * Client update error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_UPDATE_ERROR = 84;</code>
   */
  EVENT_TYPE_CLIENT_UPDATE_ERROR(84),
  /**
   * <pre>
   * Client deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_DELETE = 85;</code>
   */
  EVENT_TYPE_CLIENT_DELETE(85),
  /**
   * <pre>
   * Client deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_DELETE_ERROR = 86;</code>
   */
  EVENT_TYPE_CLIENT_DELETE_ERROR(86),
  /**
   * <pre>
   * Client-initiated account linking event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING = 87;</code>
   */
  EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING(87),
  /**
   * <pre>
   * Client-initiated account linking error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_ERROR = 88;</code>
   */
  EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_ERROR(88),
  /**
   * <pre>
   * Token exchange event
   * </pre>
   *
   * <code>EVENT_TYPE_TOKEN_EXCHANGE = 89;</code>
   */
  EVENT_TYPE_TOKEN_EXCHANGE(89),
  /**
   * <pre>
   * Token exchange error event
   * </pre>
   *
   * <code>EVENT_TYPE_TOKEN_EXCHANGE_ERROR = 90;</code>
   */
  EVENT_TYPE_TOKEN_EXCHANGE_ERROR(90),
  /**
   * <pre>
   * OAuth2 device authentication event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_AUTH = 91;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_AUTH(91),
  /**
   * <pre>
   * OAuth2 device authentication error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_AUTH_ERROR = 92;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_AUTH_ERROR(92),
  /**
   * <pre>
   * OAuth2 device user code verification event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE = 93;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE(93),
  /**
   * <pre>
   * OAuth2 device user code verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR = 94;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR(94),
  /**
   * <pre>
   * OAuth2 device code to token event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN = 95;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN(95),
  /**
   * <pre>
   * OAuth2 device code to token error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR = 96;</code>
   */
  EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR(96),
  /**
   * <pre>
   * AuthReqID to token event
   * </pre>
   *
   * <code>EVENT_TYPE_AUTHREQID_TO_TOKEN = 97;</code>
   */
  EVENT_TYPE_AUTHREQID_TO_TOKEN(97),
  /**
   * <pre>
   * AuthReqID to token error event
   * </pre>
   *
   * <code>EVENT_TYPE_AUTHREQID_TO_TOKEN_ERROR = 98;</code>
   */
  EVENT_TYPE_AUTHREQID_TO_TOKEN_ERROR(98),
  /**
   * <pre>
   * Permission token event
   * </pre>
   *
   * <code>EVENT_TYPE_PERMISSION_TOKEN = 99;</code>
   */
  EVENT_TYPE_PERMISSION_TOKEN(99),
  /**
   * <pre>
   * Permission token error event
   * </pre>
   *
   * <code>EVENT_TYPE_PERMISSION_TOKEN_ERROR = 100;</code>
   */
  EVENT_TYPE_PERMISSION_TOKEN_ERROR(100),
  /**
   * <pre>
   * Account deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_DELETE_ACCOUNT = 101;</code>
   */
  EVENT_TYPE_DELETE_ACCOUNT(101),
  /**
   * <pre>
   * Account deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_DELETE_ACCOUNT_ERROR = 102;</code>
   */
  EVENT_TYPE_DELETE_ACCOUNT_ERROR(102),
  /**
   * <pre>
   * Pushed authorization request event
   * </pre>
   *
   * <code>EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST = 103;</code>
   */
  EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST(103),
  /**
   * <pre>
   * Pushed authorization request error event
   * </pre>
   *
   * <code>EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_ERROR = 104;</code>
   */
  EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_ERROR(104),
  /**
   * <pre>
   * User disabled by permanent lockout event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT = 105;</code>
   */
  EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT(105),
  /**
   * <pre>
   * User disabled by permanent lockout error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR = 106;</code>
   */
  EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR(106),
  /**
   * <pre>
   * User disabled by temporary lockout event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT = 107;</code>
   */
  EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT(107),
  /**
   * <pre>
   * User disabled by temporary lockout error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR = 108;</code>
   */
  EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR(108),
  /**
   * <pre>
   * OAuth2 extension grant event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_EXTENSION_GRANT = 109;</code>
   */
  EVENT_TYPE_OAUTH2_EXTENSION_GRANT(109),
  /**
   * <pre>
   * OAuth2 extension grant error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_EXTENSION_GRANT_ERROR = 110;</code>
   */
  EVENT_TYPE_OAUTH2_EXTENSION_GRANT_ERROR(110),
  /**
   * <pre>
   * Federated identity override link event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK = 111;</code>
   */
  EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK(111),
  /**
   * <pre>
   * Federated identity override link error event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR = 112;</code>
   */
  EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR(112),
  /**
   * <pre>
   * Credential update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CREDENTIAL = 113;</code>
   */
  EVENT_TYPE_UPDATE_CREDENTIAL(113),
  /**
   * <pre>
   * Credential update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CREDENTIAL_ERROR = 114;</code>
   */
  EVENT_TYPE_UPDATE_CREDENTIAL_ERROR(114),
  /**
   * <pre>
   * Credential removal event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_CREDENTIAL = 115;</code>
   */
  EVENT_TYPE_REMOVE_CREDENTIAL(115),
  /**
   * <pre>
   * Credential removal error event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_CREDENTIAL_ERROR = 116;</code>
   */
  EVENT_TYPE_REMOVE_CREDENTIAL_ERROR(116),
  /**
   * <pre>
   * Organization invitation event
   * </pre>
   *
   * <code>EVENT_TYPE_INVITE_ORG = 117;</code>
   */
  EVENT_TYPE_INVITE_ORG(117),
  /**
   * <pre>
   * Organization invitation error event
   * </pre>
   *
   * <code>EVENT_TYPE_INVITE_ORG_ERROR = 118;</code>
   */
  EVENT_TYPE_INVITE_ORG_ERROR(118),
  /**
   * <pre>
   * User session deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_SESSION_DELETED = 119;</code>
   */
  EVENT_TYPE_USER_SESSION_DELETED(119),
  /**
   * <pre>
   * User session deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_SESSION_DELETED_ERROR = 120;</code>
   */
  EVENT_TYPE_USER_SESSION_DELETED_ERROR(120),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "EventType");
  }
  /**
   * <pre>
   * Invalid event type
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID = 0;</code>
   */
  public static final int EVENT_TYPE_INVALID_VALUE = 0;
  /**
   * <pre>
   * User login event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGIN = 1;</code>
   */
  public static final int EVENT_TYPE_LOGIN_VALUE = 1;
  /**
   * <pre>
   * User login error event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGIN_ERROR = 2;</code>
   */
  public static final int EVENT_TYPE_LOGIN_ERROR_VALUE = 2;
  /**
   * <pre>
   * User registration event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER = 3;</code>
   */
  public static final int EVENT_TYPE_REGISTER_VALUE = 3;
  /**
   * <pre>
   * User registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_ERROR = 4;</code>
   */
  public static final int EVENT_TYPE_REGISTER_ERROR_VALUE = 4;
  /**
   * <pre>
   * User logout event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGOUT = 5;</code>
   */
  public static final int EVENT_TYPE_LOGOUT_VALUE = 5;
  /**
   * <pre>
   * User logout error event
   * </pre>
   *
   * <code>EVENT_TYPE_LOGOUT_ERROR = 6;</code>
   */
  public static final int EVENT_TYPE_LOGOUT_ERROR_VALUE = 6;
  /**
   * <pre>
   * Authorization code to token exchange event
   * </pre>
   *
   * <code>EVENT_TYPE_CODE_TO_TOKEN = 7;</code>
   */
  public static final int EVENT_TYPE_CODE_TO_TOKEN_VALUE = 7;
  /**
   * <pre>
   * Authorization code to token exchange error event
   * </pre>
   *
   * <code>EVENT_TYPE_CODE_TO_TOKEN_ERROR = 8;</code>
   */
  public static final int EVENT_TYPE_CODE_TO_TOKEN_ERROR_VALUE = 8;
  /**
   * <pre>
   * Client login event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_LOGIN = 9;</code>
   */
  public static final int EVENT_TYPE_CLIENT_LOGIN_VALUE = 9;
  /**
   * <pre>
   * Client login error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_LOGIN_ERROR = 10;</code>
   */
  public static final int EVENT_TYPE_CLIENT_LOGIN_ERROR_VALUE = 10;
  /**
   * <pre>
   * Refresh token event
   * </pre>
   *
   * <code>EVENT_TYPE_REFRESH_TOKEN = 11;</code>
   */
  public static final int EVENT_TYPE_REFRESH_TOKEN_VALUE = 11;
  /**
   * <pre>
   * Refresh token error event
   * </pre>
   *
   * <code>EVENT_TYPE_REFRESH_TOKEN_ERROR = 12;</code>
   */
  public static final int EVENT_TYPE_REFRESH_TOKEN_ERROR_VALUE = 12;
  /**
   * <pre>
   * Access token validation event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_VALIDATE_ACCESS_TOKEN = 13 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_VALIDATE_ACCESS_TOKEN_VALUE = 13;
  /**
   * <pre>
   * Access token validation error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_VALIDATE_ACCESS_TOKEN_ERROR = 14 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_VALIDATE_ACCESS_TOKEN_ERROR_VALUE = 14;
  /**
   * <pre>
   * Token introspection event
   * </pre>
   *
   * <code>EVENT_TYPE_INTROSPECT_TOKEN = 15;</code>
   */
  public static final int EVENT_TYPE_INTROSPECT_TOKEN_VALUE = 15;
  /**
   * <pre>
   * Token introspection error event
   * </pre>
   *
   * <code>EVENT_TYPE_INTROSPECT_TOKEN_ERROR = 16;</code>
   */
  public static final int EVENT_TYPE_INTROSPECT_TOKEN_ERROR_VALUE = 16;
  /**
   * <pre>
   * Federated identity link event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_LINK = 17;</code>
   */
  public static final int EVENT_TYPE_FEDERATED_IDENTITY_LINK_VALUE = 17;
  /**
   * <pre>
   * Federated identity link error event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_LINK_ERROR = 18;</code>
   */
  public static final int EVENT_TYPE_FEDERATED_IDENTITY_LINK_ERROR_VALUE = 18;
  /**
   * <pre>
   * Federated identity removal event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_FEDERATED_IDENTITY = 19;</code>
   */
  public static final int EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_VALUE = 19;
  /**
   * <pre>
   * Federated identity removal error event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_ERROR = 20;</code>
   */
  public static final int EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_ERROR_VALUE = 20;
  /**
   * <pre>
   * Email update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_EMAIL = 21;</code>
   */
  public static final int EVENT_TYPE_UPDATE_EMAIL_VALUE = 21;
  /**
   * <pre>
   * Email update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_EMAIL_ERROR = 22;</code>
   */
  public static final int EVENT_TYPE_UPDATE_EMAIL_ERROR_VALUE = 22;
  /**
   * <pre>
   * Profile update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PROFILE = 23;</code>
   */
  public static final int EVENT_TYPE_UPDATE_PROFILE_VALUE = 23;
  /**
   * <pre>
   * Profile update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PROFILE_ERROR = 24;</code>
   */
  public static final int EVENT_TYPE_UPDATE_PROFILE_ERROR_VALUE = 24;
  /**
   * <pre>
   * Password update event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PASSWORD = 25 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_UPDATE_PASSWORD_VALUE = 25;
  /**
   * <pre>
   * Password update error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_PASSWORD_ERROR = 26 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_UPDATE_PASSWORD_ERROR_VALUE = 26;
  /**
   * <pre>
   * TOTP update event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_TOTP = 27 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_UPDATE_TOTP_VALUE = 27;
  /**
   * <pre>
   * TOTP update error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_TOTP_ERROR = 28 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_UPDATE_TOTP_ERROR_VALUE = 28;
  /**
   * <pre>
   * Email verification event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_EMAIL = 29;</code>
   */
  public static final int EVENT_TYPE_VERIFY_EMAIL_VALUE = 29;
  /**
   * <pre>
   * Email verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_EMAIL_ERROR = 30;</code>
   */
  public static final int EVENT_TYPE_VERIFY_EMAIL_ERROR_VALUE = 30;
  /**
   * <pre>
   * Profile verification event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_PROFILE = 31;</code>
   */
  public static final int EVENT_TYPE_VERIFY_PROFILE_VALUE = 31;
  /**
   * <pre>
   * Profile verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_VERIFY_PROFILE_ERROR = 32;</code>
   */
  public static final int EVENT_TYPE_VERIFY_PROFILE_ERROR_VALUE = 32;
  /**
   * <pre>
   * TOTP removal event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_TOTP = 33 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_REMOVE_TOTP_VALUE = 33;
  /**
   * <pre>
   * TOTP removal error event (deprecated)
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_TOTP_ERROR = 34 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int EVENT_TYPE_REMOVE_TOTP_ERROR_VALUE = 34;
  /**
   * <pre>
   * Consent grant event
   * </pre>
   *
   * <code>EVENT_TYPE_GRANT_CONSENT = 35;</code>
   */
  public static final int EVENT_TYPE_GRANT_CONSENT_VALUE = 35;
  /**
   * <pre>
   * Consent grant error event
   * </pre>
   *
   * <code>EVENT_TYPE_GRANT_CONSENT_ERROR = 36;</code>
   */
  public static final int EVENT_TYPE_GRANT_CONSENT_ERROR_VALUE = 36;
  /**
   * <pre>
   * Consent update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CONSENT = 37;</code>
   */
  public static final int EVENT_TYPE_UPDATE_CONSENT_VALUE = 37;
  /**
   * <pre>
   * Consent update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CONSENT_ERROR = 38;</code>
   */
  public static final int EVENT_TYPE_UPDATE_CONSENT_ERROR_VALUE = 38;
  /**
   * <pre>
   * Consent revocation event
   * </pre>
   *
   * <code>EVENT_TYPE_REVOKE_GRANT = 39;</code>
   */
  public static final int EVENT_TYPE_REVOKE_GRANT_VALUE = 39;
  /**
   * <pre>
   * Consent revocation error event
   * </pre>
   *
   * <code>EVENT_TYPE_REVOKE_GRANT_ERROR = 40;</code>
   */
  public static final int EVENT_TYPE_REVOKE_GRANT_ERROR_VALUE = 40;
  /**
   * <pre>
   * Email verification send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_VERIFY_EMAIL = 41;</code>
   */
  public static final int EVENT_TYPE_SEND_VERIFY_EMAIL_VALUE = 41;
  /**
   * <pre>
   * Email verification send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_VERIFY_EMAIL_ERROR = 42;</code>
   */
  public static final int EVENT_TYPE_SEND_VERIFY_EMAIL_ERROR_VALUE = 42;
  /**
   * <pre>
   * Password reset send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_RESET_PASSWORD = 43;</code>
   */
  public static final int EVENT_TYPE_SEND_RESET_PASSWORD_VALUE = 43;
  /**
   * <pre>
   * Password reset send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_RESET_PASSWORD_ERROR = 44;</code>
   */
  public static final int EVENT_TYPE_SEND_RESET_PASSWORD_ERROR_VALUE = 44;
  /**
   * <pre>
   * Identity provider link send event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK = 45;</code>
   */
  public static final int EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_VALUE = 45;
  /**
   * <pre>
   * Identity provider link send error event
   * </pre>
   *
   * <code>EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR = 46;</code>
   */
  public static final int EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR_VALUE = 46;
  /**
   * <pre>
   * Password reset event
   * </pre>
   *
   * <code>EVENT_TYPE_RESET_PASSWORD = 47;</code>
   */
  public static final int EVENT_TYPE_RESET_PASSWORD_VALUE = 47;
  /**
   * <pre>
   * Password reset error event
   * </pre>
   *
   * <code>EVENT_TYPE_RESET_PASSWORD_ERROR = 48;</code>
   */
  public static final int EVENT_TYPE_RESET_PASSWORD_ERROR_VALUE = 48;
  /**
   * <pre>
   * Authentication restart event
   * </pre>
   *
   * <code>EVENT_TYPE_RESTART_AUTHENTICATION = 49;</code>
   */
  public static final int EVENT_TYPE_RESTART_AUTHENTICATION_VALUE = 49;
  /**
   * <pre>
   * Authentication restart error event
   * </pre>
   *
   * <code>EVENT_TYPE_RESTART_AUTHENTICATION_ERROR = 50;</code>
   */
  public static final int EVENT_TYPE_RESTART_AUTHENTICATION_ERROR_VALUE = 50;
  /**
   * <pre>
   * Invalid signature event
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID_SIGNATURE = 51;</code>
   */
  public static final int EVENT_TYPE_INVALID_SIGNATURE_VALUE = 51;
  /**
   * <pre>
   * Invalid signature error event
   * </pre>
   *
   * <code>EVENT_TYPE_INVALID_SIGNATURE_ERROR = 52;</code>
   */
  public static final int EVENT_TYPE_INVALID_SIGNATURE_ERROR_VALUE = 52;
  /**
   * <pre>
   * Node registration event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_NODE = 53;</code>
   */
  public static final int EVENT_TYPE_REGISTER_NODE_VALUE = 53;
  /**
   * <pre>
   * Node registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_REGISTER_NODE_ERROR = 54;</code>
   */
  public static final int EVENT_TYPE_REGISTER_NODE_ERROR_VALUE = 54;
  /**
   * <pre>
   * Node unregistration event
   * </pre>
   *
   * <code>EVENT_TYPE_UNREGISTER_NODE = 55;</code>
   */
  public static final int EVENT_TYPE_UNREGISTER_NODE_VALUE = 55;
  /**
   * <pre>
   * Node unregistration error event
   * </pre>
   *
   * <code>EVENT_TYPE_UNREGISTER_NODE_ERROR = 56;</code>
   */
  public static final int EVENT_TYPE_UNREGISTER_NODE_ERROR_VALUE = 56;
  /**
   * <pre>
   * User info request event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_INFO_REQUEST = 57;</code>
   */
  public static final int EVENT_TYPE_USER_INFO_REQUEST_VALUE = 57;
  /**
   * <pre>
   * User info request error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_INFO_REQUEST_ERROR = 58;</code>
   */
  public static final int EVENT_TYPE_USER_INFO_REQUEST_ERROR_VALUE = 58;
  /**
   * <pre>
   * Identity provider account linking event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT = 59;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_VALUE = 59;
  /**
   * <pre>
   * Identity provider account linking error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR = 60;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR_VALUE = 60;
  /**
   * <pre>
   * Identity provider login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LOGIN = 61;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_VALUE = 61;
  /**
   * <pre>
   * Identity provider login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_ERROR = 62;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_ERROR_VALUE = 62;
  /**
   * <pre>
   * Identity provider first login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN = 63;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_VALUE = 63;
  /**
   * <pre>
   * Identity provider first login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR = 64;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR_VALUE = 64;
  /**
   * <pre>
   * Identity provider post-login event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN = 65;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_VALUE = 65;
  /**
   * <pre>
   * Identity provider post-login error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_ERROR = 66;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_ERROR_VALUE = 66;
  /**
   * <pre>
   * Identity provider response event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE = 67;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_VALUE = 67;
  /**
   * <pre>
   * Identity provider response error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_ERROR = 68;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_ERROR_VALUE = 68;
  /**
   * <pre>
   * Identity provider token retrieval event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN = 69;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_VALUE = 69;
  /**
   * <pre>
   * Identity provider token retrieval error event
   * </pre>
   *
   * <code>EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR = 70;</code>
   */
  public static final int EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR_VALUE = 70;
  /**
   * <pre>
   * User impersonation event
   * </pre>
   *
   * <code>EVENT_TYPE_IMPERSONATE = 71;</code>
   */
  public static final int EVENT_TYPE_IMPERSONATE_VALUE = 71;
  /**
   * <pre>
   * User impersonation error event
   * </pre>
   *
   * <code>EVENT_TYPE_IMPERSONATE_ERROR = 72;</code>
   */
  public static final int EVENT_TYPE_IMPERSONATE_ERROR_VALUE = 72;
  /**
   * <pre>
   * Custom required action event
   * </pre>
   *
   * <code>EVENT_TYPE_CUSTOM_REQUIRED_ACTION = 73;</code>
   */
  public static final int EVENT_TYPE_CUSTOM_REQUIRED_ACTION_VALUE = 73;
  /**
   * <pre>
   * Custom required action error event
   * </pre>
   *
   * <code>EVENT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR = 74;</code>
   */
  public static final int EVENT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR_VALUE = 74;
  /**
   * <pre>
   * Execute actions event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTIONS = 75;</code>
   */
  public static final int EVENT_TYPE_EXECUTE_ACTIONS_VALUE = 75;
  /**
   * <pre>
   * Execute actions error event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTIONS_ERROR = 76;</code>
   */
  public static final int EVENT_TYPE_EXECUTE_ACTIONS_ERROR_VALUE = 76;
  /**
   * <pre>
   * Execute action token event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTION_TOKEN = 77;</code>
   */
  public static final int EVENT_TYPE_EXECUTE_ACTION_TOKEN_VALUE = 77;
  /**
   * <pre>
   * Execute action token error event
   * </pre>
   *
   * <code>EVENT_TYPE_EXECUTE_ACTION_TOKEN_ERROR = 78;</code>
   */
  public static final int EVENT_TYPE_EXECUTE_ACTION_TOKEN_ERROR_VALUE = 78;
  /**
   * <pre>
   * Client info event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INFO = 79;</code>
   */
  public static final int EVENT_TYPE_CLIENT_INFO_VALUE = 79;
  /**
   * <pre>
   * Client info error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INFO_ERROR = 80;</code>
   */
  public static final int EVENT_TYPE_CLIENT_INFO_ERROR_VALUE = 80;
  /**
   * <pre>
   * Client registration event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_REGISTER = 81;</code>
   */
  public static final int EVENT_TYPE_CLIENT_REGISTER_VALUE = 81;
  /**
   * <pre>
   * Client registration error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_REGISTER_ERROR = 82;</code>
   */
  public static final int EVENT_TYPE_CLIENT_REGISTER_ERROR_VALUE = 82;
  /**
   * <pre>
   * Client update event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_UPDATE = 83;</code>
   */
  public static final int EVENT_TYPE_CLIENT_UPDATE_VALUE = 83;
  /**
   * <pre>
   * Client update error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_UPDATE_ERROR = 84;</code>
   */
  public static final int EVENT_TYPE_CLIENT_UPDATE_ERROR_VALUE = 84;
  /**
   * <pre>
   * Client deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_DELETE = 85;</code>
   */
  public static final int EVENT_TYPE_CLIENT_DELETE_VALUE = 85;
  /**
   * <pre>
   * Client deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_DELETE_ERROR = 86;</code>
   */
  public static final int EVENT_TYPE_CLIENT_DELETE_ERROR_VALUE = 86;
  /**
   * <pre>
   * Client-initiated account linking event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING = 87;</code>
   */
  public static final int EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_VALUE = 87;
  /**
   * <pre>
   * Client-initiated account linking error event
   * </pre>
   *
   * <code>EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_ERROR = 88;</code>
   */
  public static final int EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_ERROR_VALUE = 88;
  /**
   * <pre>
   * Token exchange event
   * </pre>
   *
   * <code>EVENT_TYPE_TOKEN_EXCHANGE = 89;</code>
   */
  public static final int EVENT_TYPE_TOKEN_EXCHANGE_VALUE = 89;
  /**
   * <pre>
   * Token exchange error event
   * </pre>
   *
   * <code>EVENT_TYPE_TOKEN_EXCHANGE_ERROR = 90;</code>
   */
  public static final int EVENT_TYPE_TOKEN_EXCHANGE_ERROR_VALUE = 90;
  /**
   * <pre>
   * OAuth2 device authentication event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_AUTH = 91;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_AUTH_VALUE = 91;
  /**
   * <pre>
   * OAuth2 device authentication error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_AUTH_ERROR = 92;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_AUTH_ERROR_VALUE = 92;
  /**
   * <pre>
   * OAuth2 device user code verification event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE = 93;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_VALUE = 93;
  /**
   * <pre>
   * OAuth2 device user code verification error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR = 94;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR_VALUE = 94;
  /**
   * <pre>
   * OAuth2 device code to token event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN = 95;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_VALUE = 95;
  /**
   * <pre>
   * OAuth2 device code to token error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR = 96;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR_VALUE = 96;
  /**
   * <pre>
   * AuthReqID to token event
   * </pre>
   *
   * <code>EVENT_TYPE_AUTHREQID_TO_TOKEN = 97;</code>
   */
  public static final int EVENT_TYPE_AUTHREQID_TO_TOKEN_VALUE = 97;
  /**
   * <pre>
   * AuthReqID to token error event
   * </pre>
   *
   * <code>EVENT_TYPE_AUTHREQID_TO_TOKEN_ERROR = 98;</code>
   */
  public static final int EVENT_TYPE_AUTHREQID_TO_TOKEN_ERROR_VALUE = 98;
  /**
   * <pre>
   * Permission token event
   * </pre>
   *
   * <code>EVENT_TYPE_PERMISSION_TOKEN = 99;</code>
   */
  public static final int EVENT_TYPE_PERMISSION_TOKEN_VALUE = 99;
  /**
   * <pre>
   * Permission token error event
   * </pre>
   *
   * <code>EVENT_TYPE_PERMISSION_TOKEN_ERROR = 100;</code>
   */
  public static final int EVENT_TYPE_PERMISSION_TOKEN_ERROR_VALUE = 100;
  /**
   * <pre>
   * Account deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_DELETE_ACCOUNT = 101;</code>
   */
  public static final int EVENT_TYPE_DELETE_ACCOUNT_VALUE = 101;
  /**
   * <pre>
   * Account deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_DELETE_ACCOUNT_ERROR = 102;</code>
   */
  public static final int EVENT_TYPE_DELETE_ACCOUNT_ERROR_VALUE = 102;
  /**
   * <pre>
   * Pushed authorization request event
   * </pre>
   *
   * <code>EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST = 103;</code>
   */
  public static final int EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_VALUE = 103;
  /**
   * <pre>
   * Pushed authorization request error event
   * </pre>
   *
   * <code>EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_ERROR = 104;</code>
   */
  public static final int EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_ERROR_VALUE = 104;
  /**
   * <pre>
   * User disabled by permanent lockout event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT = 105;</code>
   */
  public static final int EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_VALUE = 105;
  /**
   * <pre>
   * User disabled by permanent lockout error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR = 106;</code>
   */
  public static final int EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR_VALUE = 106;
  /**
   * <pre>
   * User disabled by temporary lockout event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT = 107;</code>
   */
  public static final int EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_VALUE = 107;
  /**
   * <pre>
   * User disabled by temporary lockout error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR = 108;</code>
   */
  public static final int EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR_VALUE = 108;
  /**
   * <pre>
   * OAuth2 extension grant event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_EXTENSION_GRANT = 109;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_EXTENSION_GRANT_VALUE = 109;
  /**
   * <pre>
   * OAuth2 extension grant error event
   * </pre>
   *
   * <code>EVENT_TYPE_OAUTH2_EXTENSION_GRANT_ERROR = 110;</code>
   */
  public static final int EVENT_TYPE_OAUTH2_EXTENSION_GRANT_ERROR_VALUE = 110;
  /**
   * <pre>
   * Federated identity override link event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK = 111;</code>
   */
  public static final int EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_VALUE = 111;
  /**
   * <pre>
   * Federated identity override link error event
   * </pre>
   *
   * <code>EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR = 112;</code>
   */
  public static final int EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR_VALUE = 112;
  /**
   * <pre>
   * Credential update event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CREDENTIAL = 113;</code>
   */
  public static final int EVENT_TYPE_UPDATE_CREDENTIAL_VALUE = 113;
  /**
   * <pre>
   * Credential update error event
   * </pre>
   *
   * <code>EVENT_TYPE_UPDATE_CREDENTIAL_ERROR = 114;</code>
   */
  public static final int EVENT_TYPE_UPDATE_CREDENTIAL_ERROR_VALUE = 114;
  /**
   * <pre>
   * Credential removal event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_CREDENTIAL = 115;</code>
   */
  public static final int EVENT_TYPE_REMOVE_CREDENTIAL_VALUE = 115;
  /**
   * <pre>
   * Credential removal error event
   * </pre>
   *
   * <code>EVENT_TYPE_REMOVE_CREDENTIAL_ERROR = 116;</code>
   */
  public static final int EVENT_TYPE_REMOVE_CREDENTIAL_ERROR_VALUE = 116;
  /**
   * <pre>
   * Organization invitation event
   * </pre>
   *
   * <code>EVENT_TYPE_INVITE_ORG = 117;</code>
   */
  public static final int EVENT_TYPE_INVITE_ORG_VALUE = 117;
  /**
   * <pre>
   * Organization invitation error event
   * </pre>
   *
   * <code>EVENT_TYPE_INVITE_ORG_ERROR = 118;</code>
   */
  public static final int EVENT_TYPE_INVITE_ORG_ERROR_VALUE = 118;
  /**
   * <pre>
   * User session deletion event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_SESSION_DELETED = 119;</code>
   */
  public static final int EVENT_TYPE_USER_SESSION_DELETED_VALUE = 119;
  /**
   * <pre>
   * User session deletion error event
   * </pre>
   *
   * <code>EVENT_TYPE_USER_SESSION_DELETED_ERROR = 120;</code>
   */
  public static final int EVENT_TYPE_USER_SESSION_DELETED_ERROR_VALUE = 120;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EventType forNumber(int value) {
    switch (value) {
      case 0: return EVENT_TYPE_INVALID;
      case 1: return EVENT_TYPE_LOGIN;
      case 2: return EVENT_TYPE_LOGIN_ERROR;
      case 3: return EVENT_TYPE_REGISTER;
      case 4: return EVENT_TYPE_REGISTER_ERROR;
      case 5: return EVENT_TYPE_LOGOUT;
      case 6: return EVENT_TYPE_LOGOUT_ERROR;
      case 7: return EVENT_TYPE_CODE_TO_TOKEN;
      case 8: return EVENT_TYPE_CODE_TO_TOKEN_ERROR;
      case 9: return EVENT_TYPE_CLIENT_LOGIN;
      case 10: return EVENT_TYPE_CLIENT_LOGIN_ERROR;
      case 11: return EVENT_TYPE_REFRESH_TOKEN;
      case 12: return EVENT_TYPE_REFRESH_TOKEN_ERROR;
      case 13: return EVENT_TYPE_VALIDATE_ACCESS_TOKEN;
      case 14: return EVENT_TYPE_VALIDATE_ACCESS_TOKEN_ERROR;
      case 15: return EVENT_TYPE_INTROSPECT_TOKEN;
      case 16: return EVENT_TYPE_INTROSPECT_TOKEN_ERROR;
      case 17: return EVENT_TYPE_FEDERATED_IDENTITY_LINK;
      case 18: return EVENT_TYPE_FEDERATED_IDENTITY_LINK_ERROR;
      case 19: return EVENT_TYPE_REMOVE_FEDERATED_IDENTITY;
      case 20: return EVENT_TYPE_REMOVE_FEDERATED_IDENTITY_ERROR;
      case 21: return EVENT_TYPE_UPDATE_EMAIL;
      case 22: return EVENT_TYPE_UPDATE_EMAIL_ERROR;
      case 23: return EVENT_TYPE_UPDATE_PROFILE;
      case 24: return EVENT_TYPE_UPDATE_PROFILE_ERROR;
      case 25: return EVENT_TYPE_UPDATE_PASSWORD;
      case 26: return EVENT_TYPE_UPDATE_PASSWORD_ERROR;
      case 27: return EVENT_TYPE_UPDATE_TOTP;
      case 28: return EVENT_TYPE_UPDATE_TOTP_ERROR;
      case 29: return EVENT_TYPE_VERIFY_EMAIL;
      case 30: return EVENT_TYPE_VERIFY_EMAIL_ERROR;
      case 31: return EVENT_TYPE_VERIFY_PROFILE;
      case 32: return EVENT_TYPE_VERIFY_PROFILE_ERROR;
      case 33: return EVENT_TYPE_REMOVE_TOTP;
      case 34: return EVENT_TYPE_REMOVE_TOTP_ERROR;
      case 35: return EVENT_TYPE_GRANT_CONSENT;
      case 36: return EVENT_TYPE_GRANT_CONSENT_ERROR;
      case 37: return EVENT_TYPE_UPDATE_CONSENT;
      case 38: return EVENT_TYPE_UPDATE_CONSENT_ERROR;
      case 39: return EVENT_TYPE_REVOKE_GRANT;
      case 40: return EVENT_TYPE_REVOKE_GRANT_ERROR;
      case 41: return EVENT_TYPE_SEND_VERIFY_EMAIL;
      case 42: return EVENT_TYPE_SEND_VERIFY_EMAIL_ERROR;
      case 43: return EVENT_TYPE_SEND_RESET_PASSWORD;
      case 44: return EVENT_TYPE_SEND_RESET_PASSWORD_ERROR;
      case 45: return EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK;
      case 46: return EVENT_TYPE_SEND_IDENTITY_PROVIDER_LINK_ERROR;
      case 47: return EVENT_TYPE_RESET_PASSWORD;
      case 48: return EVENT_TYPE_RESET_PASSWORD_ERROR;
      case 49: return EVENT_TYPE_RESTART_AUTHENTICATION;
      case 50: return EVENT_TYPE_RESTART_AUTHENTICATION_ERROR;
      case 51: return EVENT_TYPE_INVALID_SIGNATURE;
      case 52: return EVENT_TYPE_INVALID_SIGNATURE_ERROR;
      case 53: return EVENT_TYPE_REGISTER_NODE;
      case 54: return EVENT_TYPE_REGISTER_NODE_ERROR;
      case 55: return EVENT_TYPE_UNREGISTER_NODE;
      case 56: return EVENT_TYPE_UNREGISTER_NODE_ERROR;
      case 57: return EVENT_TYPE_USER_INFO_REQUEST;
      case 58: return EVENT_TYPE_USER_INFO_REQUEST_ERROR;
      case 59: return EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT;
      case 60: return EVENT_TYPE_IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR;
      case 61: return EVENT_TYPE_IDENTITY_PROVIDER_LOGIN;
      case 62: return EVENT_TYPE_IDENTITY_PROVIDER_LOGIN_ERROR;
      case 63: return EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN;
      case 64: return EVENT_TYPE_IDENTITY_PROVIDER_FIRST_LOGIN_ERROR;
      case 65: return EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN;
      case 66: return EVENT_TYPE_IDENTITY_PROVIDER_POST_LOGIN_ERROR;
      case 67: return EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE;
      case 68: return EVENT_TYPE_IDENTITY_PROVIDER_RESPONSE_ERROR;
      case 69: return EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN;
      case 70: return EVENT_TYPE_IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR;
      case 71: return EVENT_TYPE_IMPERSONATE;
      case 72: return EVENT_TYPE_IMPERSONATE_ERROR;
      case 73: return EVENT_TYPE_CUSTOM_REQUIRED_ACTION;
      case 74: return EVENT_TYPE_CUSTOM_REQUIRED_ACTION_ERROR;
      case 75: return EVENT_TYPE_EXECUTE_ACTIONS;
      case 76: return EVENT_TYPE_EXECUTE_ACTIONS_ERROR;
      case 77: return EVENT_TYPE_EXECUTE_ACTION_TOKEN;
      case 78: return EVENT_TYPE_EXECUTE_ACTION_TOKEN_ERROR;
      case 79: return EVENT_TYPE_CLIENT_INFO;
      case 80: return EVENT_TYPE_CLIENT_INFO_ERROR;
      case 81: return EVENT_TYPE_CLIENT_REGISTER;
      case 82: return EVENT_TYPE_CLIENT_REGISTER_ERROR;
      case 83: return EVENT_TYPE_CLIENT_UPDATE;
      case 84: return EVENT_TYPE_CLIENT_UPDATE_ERROR;
      case 85: return EVENT_TYPE_CLIENT_DELETE;
      case 86: return EVENT_TYPE_CLIENT_DELETE_ERROR;
      case 87: return EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING;
      case 88: return EVENT_TYPE_CLIENT_INITIATED_ACCOUNT_LINKING_ERROR;
      case 89: return EVENT_TYPE_TOKEN_EXCHANGE;
      case 90: return EVENT_TYPE_TOKEN_EXCHANGE_ERROR;
      case 91: return EVENT_TYPE_OAUTH2_DEVICE_AUTH;
      case 92: return EVENT_TYPE_OAUTH2_DEVICE_AUTH_ERROR;
      case 93: return EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE;
      case 94: return EVENT_TYPE_OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR;
      case 95: return EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN;
      case 96: return EVENT_TYPE_OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR;
      case 97: return EVENT_TYPE_AUTHREQID_TO_TOKEN;
      case 98: return EVENT_TYPE_AUTHREQID_TO_TOKEN_ERROR;
      case 99: return EVENT_TYPE_PERMISSION_TOKEN;
      case 100: return EVENT_TYPE_PERMISSION_TOKEN_ERROR;
      case 101: return EVENT_TYPE_DELETE_ACCOUNT;
      case 102: return EVENT_TYPE_DELETE_ACCOUNT_ERROR;
      case 103: return EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST;
      case 104: return EVENT_TYPE_PUSHED_AUTHORIZATION_REQUEST_ERROR;
      case 105: return EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT;
      case 106: return EVENT_TYPE_USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR;
      case 107: return EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT;
      case 108: return EVENT_TYPE_USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR;
      case 109: return EVENT_TYPE_OAUTH2_EXTENSION_GRANT;
      case 110: return EVENT_TYPE_OAUTH2_EXTENSION_GRANT_ERROR;
      case 111: return EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK;
      case 112: return EVENT_TYPE_FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR;
      case 113: return EVENT_TYPE_UPDATE_CREDENTIAL;
      case 114: return EVENT_TYPE_UPDATE_CREDENTIAL_ERROR;
      case 115: return EVENT_TYPE_REMOVE_CREDENTIAL;
      case 116: return EVENT_TYPE_REMOVE_CREDENTIAL_ERROR;
      case 117: return EVENT_TYPE_INVITE_ORG;
      case 118: return EVENT_TYPE_INVITE_ORG_ERROR;
      case 119: return EVENT_TYPE_USER_SESSION_DELETED;
      case 120: return EVENT_TYPE_USER_SESSION_DELETED_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
          public EventType findValueByNumber(int number) {
            return EventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.keycloak.event.v1.EventProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final EventType[] VALUES = values();

  public static EventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:keycloak.event.v1.EventType)
}

